//! `replay_tape_baselines` byte-determinism lock.
//!
//! Pairs with `tests/live_tape_replay_is_deterministic.rs`. That
//! test pins: given a tape, the motif engine produces a byte-stable
//! episode stream. This test pins the same property for the
//! *baseline* scoring path: given a tape + ground truth, the
//! bakeoff CSV (DSFB + ADWIN + BOCPD + PELT scored by
//! `metrics::evaluate`) is byte-stable across re-invocations.
//!
//! If this test drifts, either a detector has lost determinism
//! (a HashMap iteration leak, a floating-point ordering dependency,
//! a system-clock read) or the CSV writer has developed locale
//! sensitivity. Either way the 7th non-claim's "tape → episodes is
//! byte-stable" promise must be renegotiated.
//!
//! Skipped unless the pinned fixture tape and its ground truth are
//! present under `paper/fixtures/live_pg_real/`. The fixtures are
//! captured artefacts, not regenerated by CI.

#![cfg(feature = "live-postgres")]

use std::path::{Path, PathBuf};
use std::process::Command;

fn crate_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

fn fixture_paths() -> (PathBuf, PathBuf, PathBuf) {
    let root = crate_root();
    let tape = root.join("paper/fixtures/live_pg_real/replication_01.tape.jsonl");
    let manifest = root.join("paper/fixtures/live_pg_real/replication_01.tape.jsonl.hash");
    let gt = root.join("paper/fixtures/live_pg_real/ground_truth.json");
    (tape, manifest, gt)
}

fn bin_path() -> PathBuf {
    let mut p = crate_root();
    p.push("target/release/replay_tape_baselines");
    p
}

fn have_fixtures_and_bin() -> bool {
    let (tape, manifest, gt) = fixture_paths();
    tape.exists() && manifest.exists() && gt.exists() && bin_path().exists()
}

fn run_bakeoff(out_dir: &Path) -> Vec<u8> {
    let (tape, _, gt) = fixture_paths();
    let status = Command::new(bin_path())
        .arg("--tape")
        .arg(&tape)
        .arg("--ground-truth")
        .arg(&gt)
        .arg("--out")
        .arg(out_dir)
        .status()
        .expect("invoking replay_tape_baselines");
    assert!(status.success(), "replay_tape_baselines exited non-zero");
    let csv = out_dir.join("bakeoff.csv");
    std::fs::read(&csv).expect("reading bakeoff.csv")
}

#[test]
fn replay_tape_baselines_is_byte_deterministic() {
    if !have_fixtures_and_bin() {
        eprintln!(
            "skipping: requires pinned fixture + release-built binary. \
             run: cargo build --release --features \"cli report live-postgres\""
        );
        return;
    }
    let dir1 = tempfile::tempdir().unwrap();
    let dir2 = tempfile::tempdir().unwrap();
    let a = run_bakeoff(dir1.path());
    let b = run_bakeoff(dir2.path());
    assert_eq!(
        a, b,
        "bakeoff CSV differs across two invocations on the pinned tape + ground truth: \
         either a detector is non-deterministic or the scoring path has drifted"
    );
    assert!(!a.is_empty(), "bakeoff CSV is unexpectedly empty");
    // Sanity: header rows present, plus 4 detectors * 5 motifs = 20 data rows.
    let text = std::str::from_utf8(&a).expect("bakeoff CSV is valid UTF-8");
    let data_rows = text
        .lines()
        .filter(|l| !l.is_empty() && !l.starts_with('#') && !l.starts_with("detector,"))
        .count();
    assert_eq!(
        data_rows, 20,
        "expected 4 detectors × 5 motifs = 20 data rows; got {}",
        data_rows
    );
}
