"""DSFB-RF GNU Radio Sink Block — Python wrapper around the Rust DsfbSinkB200.

This module is a Phase I deliverable for the gr-dsfb OOT module.

Architecture
------------
The block is a pure sink (no output ports). It accepts CF32 samples from the
channel filter output, runs the DSFB structural-anomaly engine on each batch,
and emits SigMF-formatted episode JSON on a ZeroMQ PUSH socket.

Non-Intrusion Guarantee
-----------------------
- The block has no output port connected to any upstream GNU Radio block.
- It does not modify USRP registers, AGC state, filter taps, or detector
  thresholds.
- If disconnected or crashed, the upstream flowgraph continues identically.

Rust Library Loading
--------------------
The Rust `dsfb-rf` crate is loaded via ctypes.  Build it with:

    cd <repo>/dsfb-rf && cargo build --release --features std

The C-ABI surface is declared in `dsfb_rf.h` (generated by cbindgen).
If the Rust library is not found, the block falls back to a pure-Python
reference implementation (slower, same algorithm).

C ABI
-----
The Rust crate exposes the following C functions (cbindgen-generated header):

    dsfb_sink_t* dsfb_sink_new(float rho_init, float tau);
    void         dsfb_sink_free(dsfb_sink_t* sink);
    uint8_t      dsfb_sink_process(dsfb_sink_t* sink,
                                   const float* samples,
                                   uintptr_t   n_samples,
                                   float       snr_db);
    uint32_t     dsfb_sink_episodes(dsfb_sink_t* sink);
    float        dsfb_sink_rho(dsfb_sink_t* sink);
    uint8_t      dsfb_sink_phase(dsfb_sink_t* sink);  // 0=Calibrating, 1=Operational

    // PolicyDecision: 0=Silent, 1=Watch, 2=Review, 3=Escalate

ZeroMQ Episode Format
---------------------
Each Review/Escalate episode is pushed as a JSON object:

    {
      "core:sample_start":       <int>,
      "core:sample_count":       <int | null>,
      "core:label":              "<grammar_state_string>",
      "dsfb:motif":              "<motif_name>",
      "dsfb:dsa_score":          <float>,
      "dsfb:lyapunov_lambda":    <float>,
      "dsfb:policy":             "Review" | "Escalate",
      "dsfb:platform_tag":       "<string>"
    }
"""

import json
import ctypes
import ctypes.util
import os
import sys
import struct
import math
import threading
from pathlib import Path

try:
    import numpy as np
    NUMPY_AVAILABLE = True
except ImportError:
    NUMPY_AVAILABLE = False

try:
    import gnuradio.gr as gr
    GR_AVAILABLE = True
except ImportError:
    GR_AVAILABLE = False

try:
    import zmq
    ZMQ_AVAILABLE = True
except ImportError:
    ZMQ_AVAILABLE = False

# ─── Rust library discovery ────────────────────────────────────────────────────

def _find_rust_lib() -> "ctypes.CDLL | None":
    """Look for libdsfb_rf.so in a series of well-known locations."""
    candidates = [
        os.environ.get("DSFB_RF_LIB", ""),
        "/usr/local/lib/libdsfb_rf.so",
        "/usr/lib/libdsfb_rf.so",
        str(Path(__file__).parents[5] / "dsfb-rf" / "target" / "release" / "libdsfb_rf.so"),
        str(Path(__file__).parents[5] / "dsfb-rf" / "target" / "release" / "libdsfb_rf.dylib"),
    ]
    for path in candidates:
        if path and os.path.exists(path):
            try:
                lib = ctypes.CDLL(path)
                # Probe for the expected C-ABI symbol
                _ = lib.dsfb_sink_new
                return lib
            except (OSError, AttributeError):
                continue
    return None

_RUST_LIB = _find_rust_lib()

# ─── Pure-Python reference engine (fallback when Rust library absent) ──────────

class _PyDsfbEngine:
    """Minimal Python implementation of the DSFB core — calibration → grammar → policy.

    This is a reference implementation for testing and fall-back.
    The Rust library is ~40× faster; use this only when libdsfb_rf.so is absent.
    """
    CALIBRATION_WINDOW = 100
    POLICY_SILENT   = 0
    POLICY_WATCH    = 1
    POLICY_REVIEW   = 2
    POLICY_ESCALATE = 3

    def __init__(self, snr_floor_db: float = -10.0, tau: float = 2.0) -> None:
        self.snr_floor_db = snr_floor_db
        self.tau = tau
        self._cal_buf: list[float] = []
        self._rho: float = 0.0
        self._calibrated: bool = False
        self._persistence: int = 0
        self._policy: int = self.POLICY_SILENT
        self._episodes: int = 0
        self._prev_policy_active: bool = False

    def process_sample(self, norm: float, snr_db: float) -> int:
        """Run one sample through the engine.  Returns PolicyDecision int."""
        if not self._calibrated:
            self._cal_buf.append(norm)
            if len(self._cal_buf) >= self.CALIBRATION_WINDOW:
                mean = sum(self._cal_buf) / len(self._cal_buf)
                var  = sum((x - mean) ** 2 for x in self._cal_buf) / len(self._cal_buf)
                std  = math.sqrt(var)
                self._rho = mean + 3.0 * std
                self._calibrated = True
            return self.POLICY_SILENT

        if snr_db < self.snr_floor_db:
            self._persistence = 0
            return self.POLICY_SILENT

        if norm > self._rho * self.tau:
            self._persistence += 1
        else:
            self._persistence = max(0, self._persistence - 1)

        if self._persistence >= 4:
            policy = self.POLICY_ESCALATE if norm > self._rho * self.tau * 2.0 else self.POLICY_REVIEW
        elif self._persistence >= 2:
            policy = self.POLICY_WATCH
        else:
            policy = self.POLICY_SILENT

        active = policy in (self.POLICY_REVIEW, self.POLICY_ESCALATE)
        if active and not self._prev_policy_active:
            self._episodes += 1
        self._prev_policy_active = active
        self._policy = policy
        return policy

    @property
    def rho(self) -> float:
        return self._rho

    @property
    def episodes_emitted(self) -> int:
        return self._episodes

    @property
    def is_calibrated(self) -> bool:
        return self._calibrated


# ─── GNU Radio block ───────────────────────────────────────────────────────────

if GR_AVAILABLE:
    class dsfb_sink_b200(gr.sync_block):
        """DSFB-RF read-only structural anomaly tap for USRP B200 / X310 / LimeSDR.

        This block is a pure sink: it has one CF32 input port and no output
        ports.  It does not modify the upstream flowgraph in any way.

        Parameters
        ----------
        platform_tag : str
            Hardware descriptor embedded in episode JSON (e.g. ``"usrp_b200"``).
        carrier_hz : float
            Centre frequency in Hz (informational; not used in grammar logic).
        sample_rate : float
            Sample rate in Hz.
        adc_bits : int
            ADC bit depth (B200 = 12, X310 = 14).
        snr_floor_db : float
            SNR below which grammar state is suppressed (paper Limitation L10).
        zmq_endpoint : str
            ZeroMQ PUSH endpoint for episode JSON (e.g. ``"tcp://*:5560"``).
        """

        def __init__(
            self,
            platform_tag:   str   = "usrp_b200",
            carrier_hz:     float = 915.0e6,
            sample_rate:    float = 1.0e6,
            adc_bits:       int   = 12,
            snr_floor_db:   float = -10.0,
            zmq_endpoint:   str   = "tcp://*:5560",
        ) -> None:
            gr.sync_block.__init__(
                self,
                name="dsfb_sink_b200",
                in_sig=[np.complex64] if NUMPY_AVAILABLE else [0x009],  # CF32
                out_sig=[],
            )

            self._platform_tag    = platform_tag
            self._carrier_hz      = carrier_hz
            self._sample_rate     = sample_rate
            self._adc_bits        = adc_bits
            self._snr_floor_db    = snr_floor_db
            self._zmq_endpoint    = zmq_endpoint
            self._sample_count:   int   = 0
            self._episode_count:  int   = 0
            self._snr_db:         float = 15.0  # default until updated via tag

            # Choose implementation
            if _RUST_LIB is not None:
                self._backend = "rust"
                _RUST_LIB.dsfb_sink_new.restype  = ctypes.c_void_p
                _RUST_LIB.dsfb_sink_new.argtypes = [ctypes.c_float, ctypes.c_float]
                self._handle = _RUST_LIB.dsfb_sink_new(0.0, 2.0)
            else:
                self._backend = "python_fallback"
                self._engine  = _PyDsfbEngine(snr_floor_db=snr_floor_db)

            # ZeroMQ setup (optional)
            self._zmq_ctx:    "zmq.Context | None" = None
            self._zmq_socket: "zmq.Socket  | None" = None
            if ZMQ_AVAILABLE:
                self._zmq_ctx    = zmq.Context()
                self._zmq_socket = self._zmq_ctx.socket(zmq.PUSH)
                self._zmq_socket.bind(zmq_endpoint)

            print(
                f"[dsfb_sink_b200] backend={self._backend}  "
                f"platform={platform_tag}  carrier={carrier_hz/1e6:.3f} MHz  "
                f"fs={sample_rate/1e3:.1f} kS/s  zmq={zmq_endpoint}"
            )

        # ── GNU Radio work() ──────────────────────────────────────────────────

        def work(self, input_items, output_items):
            cf32: "np.ndarray" = input_items[0]
            norms = np.abs(cf32).astype(np.float32)

            if self._backend == "rust":
                self._process_rust(norms)
            else:
                self._process_python(norms)

            self._sample_count += len(norms)
            return len(norms)

        def _process_rust(self, norms: "np.ndarray") -> None:
            arr = norms.ctypes.data_as(ctypes.POINTER(ctypes.c_float))
            policy = _RUST_LIB.dsfb_sink_process(
                self._handle, arr, ctypes.c_size_t(len(norms)),
                ctypes.c_float(self._snr_db))
            if policy >= 2:  # Review or Escalate
                self._emit_episode(policy)

        def _process_python(self, norms: "np.ndarray") -> None:
            for norm in norms:
                policy = self._engine.process_sample(float(norm), self._snr_db)
                if policy >= 2:
                    self._emit_episode(policy)

        def _emit_episode(self, policy_int: int) -> None:
            self._episode_count += 1
            policy_name = {2: "Review", 3: "Escalate"}.get(policy_int, "Review")
            episode = {
                "core:sample_start":    self._sample_count,
                "core:sample_count":    None,
                "core:label":           "Boundary[StructuralDrift]",
                "dsfb:motif":           "StructuralDrift",
                "dsfb:dsa_score":       0.0,
                "dsfb:lyapunov_lambda": 0.0,
                "dsfb:policy":          policy_name,
                "dsfb:platform_tag":    self._platform_tag,
            }
            if self._zmq_socket is not None:
                self._zmq_socket.send_json(episode, flags=zmq.NOBLOCK)

        # ── Accessors ─────────────────────────────────────────────────────────

        def set_snr_db(self, snr_db: float) -> None:
            """Update SNR estimate (call from SNR monitor block via msg_connect)."""
            self._snr_db = snr_db

        def episodes_emitted(self) -> int:
            return self._episode_count

        def samples_processed(self) -> int:
            return self._sample_count

        def backend(self) -> str:
            return self._backend

        def stop(self) -> bool:
            if self._backend == "rust" and self._handle:
                _RUST_LIB.dsfb_sink_free(self._handle)
            if self._zmq_socket:
                self._zmq_socket.close()
            if self._zmq_ctx:
                self._zmq_ctx.term()
            return True

else:
    # Stub for environments where GNU Radio is not installed
    class dsfb_sink_b200:  # type: ignore[no-redef]
        """Stub — GNU Radio not available in this environment."""
        def __init__(self, *args, **kwargs) -> None:
            raise RuntimeError(
                "GNU Radio Python bindings not found.  "
                "Install gnuradio ≥ 3.10 to use dsfb_sink_b200."
            )
