//! Builtin typed heuristic-bank entry content for deterministic fallback runs.

use crate::engine::types::{
    AdmissibilityRequirement, HeuristicBankEntry, HeuristicProvenance, HeuristicScopeConditions,
};

pub(super) fn builtin_heuristic_bank_entries_impl() -> Vec<HeuristicBankEntry> {
    vec![
        HeuristicBankEntry {
            heuristic_id: "H-PERSISTENT-OUTWARD-DRIFT".to_string(),
            motif_label: "gradual degradation candidate".to_string(),
            short_label: "persistent_outward".to_string(),
            scope_conditions: HeuristicScopeConditions {
                min_outward_drift_fraction: Some(0.60),
                max_outward_drift_fraction: None,
                min_inward_drift_fraction: None,
                max_inward_drift_fraction: Some(0.30),
                max_curvature_energy: Some(3.0e-9),
                min_curvature_energy: None,
                max_curvature_onset_score: Some(0.25),
                min_curvature_onset_score: None,
                min_directional_persistence: Some(0.65),
                min_sign_consistency: Some(0.60),
                min_channel_coherence: Some(0.55),
                min_aggregate_monotonicity: Some(0.72),
                max_aggregate_monotonicity: None,
                min_slew_spike_count: None,
                max_slew_spike_count: Some(1),
                min_slew_spike_strength: None,
                max_slew_spike_strength: Some(0.01),
                min_boundary_grazing_episodes: None,
                max_boundary_grazing_episodes: None,
                min_boundary_recovery_count: None,
                min_coordinated_group_breach_fraction: None,
                max_coordinated_group_breach_fraction: Some(0.05),
                require_group_breach: false,
            },
            admissibility_requirements: AdmissibilityRequirement::NoViolation,
            regime_tags: vec![
                "fixed".to_string(),
                "widening".to_string(),
                "regime_shifted".to_string(),
            ],
            provenance: HeuristicProvenance {
                source: "typed heuristic bank".to_string(),
                note: "Illustrative mapping from persistent outward drift syntax to a conservative degradation-style motif.".to_string(),
            },
            applicability_note: "Use only as an admissibility-qualified drift motif. It does not determine underlying physical cause.".to_string(),
            retrieval_priority: 90,
            compatible_with: vec![
                "H-BOUNDARY-GRAZING".to_string(),
                "H-COORDINATED-RISE".to_string(),
            ],
            incompatible_with: vec![
                "H-PERSISTENT-ADMISSIBILITY-DEPARTURE".to_string(),
                "H-DISCRETE-EVENT".to_string(),
                "H-CURVATURE-RICH-TRANSITION".to_string(),
                "H-CURVATURE-LED-DEPARTURE".to_string(),
                "H-MIXED-REGIME-TRANSITION".to_string(),
                "H-INWARD-CONTAINMENT".to_string(),
                "H-INWARD-RECOVERY".to_string(),
                "H-BOUNDED-OSCILLATORY".to_string(),
                "H-STRUCTURED-NOISY-TRAJECTORY".to_string(),
                "H-BASELINE-COMPATIBLE".to_string(),
            ],
            directional_incompatibility_exceptions: Vec::new(),
        },
        HeuristicBankEntry {
            heuristic_id: "H-PERSISTENT-ADMISSIBILITY-DEPARTURE".to_string(),
            motif_label: "persistent admissibility departure candidate".to_string(),
            short_label: "persistent_departure".to_string(),
            scope_conditions: HeuristicScopeConditions {
                min_outward_drift_fraction: Some(0.75),
                max_outward_drift_fraction: None,
                min_inward_drift_fraction: None,
                max_inward_drift_fraction: Some(0.20),
                max_curvature_energy: Some(1.0e-6),
                min_curvature_energy: None,
                max_curvature_onset_score: Some(0.25),
                min_curvature_onset_score: None,
                min_directional_persistence: Some(0.70),
                min_sign_consistency: Some(0.70),
                min_channel_coherence: Some(0.50),
                min_aggregate_monotonicity: Some(0.80),
                max_aggregate_monotonicity: None,
                min_slew_spike_count: None,
                max_slew_spike_count: Some(1),
                min_slew_spike_strength: None,
                max_slew_spike_strength: Some(0.01),
                min_boundary_grazing_episodes: None,
                max_boundary_grazing_episodes: None,
                min_boundary_recovery_count: None,
                min_coordinated_group_breach_fraction: None,
                max_coordinated_group_breach_fraction: Some(0.05),
                require_group_breach: false,
            },
            admissibility_requirements: AdmissibilityRequirement::ViolationRequired,
            regime_tags: vec![
                "fixed".to_string(),
                "widening".to_string(),
                "regime_shifted".to_string(),
            ],
            provenance: HeuristicProvenance {
                source: "typed heuristic bank".to_string(),
                note: "Illustrative mapping from sustained outward residual migration with actual admissibility breach to a conservative departure motif.".to_string(),
            },
            applicability_note: "Use only when sustained outward structure remains dominant after a configured envelope breach. This does not identify the underlying mechanism uniquely.".to_string(),
            retrieval_priority: 89,
            compatible_with: Vec::new(),
            incompatible_with: vec![
                "H-PERSISTENT-OUTWARD-DRIFT".to_string(),
                "H-DISCRETE-EVENT".to_string(),
                "H-CURVATURE-RICH-TRANSITION".to_string(),
                "H-CURVATURE-LED-DEPARTURE".to_string(),
                "H-INWARD-CONTAINMENT".to_string(),
                "H-MIXED-REGIME-TRANSITION".to_string(),
                "H-BOUNDARY-GRAZING".to_string(),
                "H-RECURRENT-BOUNDARY-RECURRENCE".to_string(),
                "H-COORDINATED-RISE".to_string(),
                "H-INWARD-RECOVERY".to_string(),
                "H-BOUNDED-OSCILLATORY".to_string(),
                "H-STRUCTURED-NOISY-TRAJECTORY".to_string(),
                "H-BASELINE-COMPATIBLE".to_string(),
            ],
            directional_incompatibility_exceptions: Vec::new(),
        },
        HeuristicBankEntry {
            heuristic_id: "H-DISCRETE-EVENT".to_string(),
            motif_label: "discrete event candidate".to_string(),
            short_label: "discrete_event".to_string(),
            scope_conditions: HeuristicScopeConditions {
                min_outward_drift_fraction: None,
                max_outward_drift_fraction: None,
                min_inward_drift_fraction: None,
                max_inward_drift_fraction: None,
                max_curvature_energy: None,
                min_curvature_energy: Some(2.0e-6),
                max_curvature_onset_score: None,
                min_curvature_onset_score: Some(0.20),
                min_directional_persistence: None,
                min_sign_consistency: None,
                min_channel_coherence: None,
                min_aggregate_monotonicity: None,
                max_aggregate_monotonicity: None,
                min_slew_spike_count: Some(1),
                max_slew_spike_count: None,
                min_slew_spike_strength: Some(0.05),
                max_slew_spike_strength: None,
                min_boundary_grazing_episodes: None,
                max_boundary_grazing_episodes: None,
                min_boundary_recovery_count: None,
                min_coordinated_group_breach_fraction: None,
                max_coordinated_group_breach_fraction: None,
                require_group_breach: false,
            },
            admissibility_requirements: AdmissibilityRequirement::Any,
            regime_tags: vec![
                "fixed".to_string(),
                "widening".to_string(),
                "regime_shifted".to_string(),
            ],
            provenance: HeuristicProvenance {
                source: "typed heuristic bank".to_string(),
                note: "Illustrative mapping from localized high-slew activity to an abrupt-event-like motif.".to_string(),
            },
            applicability_note: "Treat as an event-compatible motif only. Multiple abrupt or switching mechanisms may produce similar signatures.".to_string(),
            retrieval_priority: 85,
            compatible_with: vec!["H-CURVATURE-RICH-TRANSITION".to_string()],
            incompatible_with: vec![
                "H-PERSISTENT-OUTWARD-DRIFT".to_string(),
                "H-PERSISTENT-ADMISSIBILITY-DEPARTURE".to_string(),
                "H-CURVATURE-LED-DEPARTURE".to_string(),
                "H-INWARD-CONTAINMENT".to_string(),
                "H-INWARD-RECOVERY".to_string(),
                "H-BOUNDED-OSCILLATORY".to_string(),
                "H-STRUCTURED-NOISY-TRAJECTORY".to_string(),
                "H-BASELINE-COMPATIBLE".to_string(),
            ],
            directional_incompatibility_exceptions: Vec::new(),
        },
        HeuristicBankEntry {
            heuristic_id: "H-CURVATURE-RICH-TRANSITION".to_string(),
            motif_label: "curvature-rich transition candidate".to_string(),
            short_label: "curvature_transition".to_string(),
            scope_conditions: HeuristicScopeConditions {
                min_outward_drift_fraction: None,
                max_outward_drift_fraction: None,
                min_inward_drift_fraction: None,
                max_inward_drift_fraction: None,
                max_curvature_energy: None,
                min_curvature_energy: Some(4.0e-9),
                max_curvature_onset_score: None,
                min_curvature_onset_score: Some(0.15),
                min_directional_persistence: None,
                min_sign_consistency: None,
                min_channel_coherence: Some(0.30),
                min_aggregate_monotonicity: None,
                max_aggregate_monotonicity: None,
                min_slew_spike_count: Some(1),
                max_slew_spike_count: None,
                min_slew_spike_strength: Some(0.01),
                max_slew_spike_strength: None,
                min_boundary_grazing_episodes: None,
                max_boundary_grazing_episodes: None,
                min_boundary_recovery_count: None,
                min_coordinated_group_breach_fraction: None,
                max_coordinated_group_breach_fraction: None,
                require_group_breach: false,
            },
            admissibility_requirements: AdmissibilityRequirement::Any,
            regime_tags: vec![
                "fixed".to_string(),
                "widening".to_string(),
                "regime_shifted".to_string(),
            ],
            provenance: HeuristicProvenance {
                source: "typed heuristic bank".to_string(),
                note: "Illustrative mapping for residual trajectories whose interpretation is governed more by curvature than by monotone migration.".to_string(),
            },
            applicability_note: "Use when slew-rich structure is material. This remains a motif statement, not a validated mechanism classifier.".to_string(),
            retrieval_priority: 80,
            compatible_with: vec![
                "H-DISCRETE-EVENT".to_string(),
                "H-MIXED-REGIME-TRANSITION".to_string(),
            ],
            incompatible_with: vec![
                "H-PERSISTENT-OUTWARD-DRIFT".to_string(),
                "H-PERSISTENT-ADMISSIBILITY-DEPARTURE".to_string(),
                "H-CURVATURE-LED-DEPARTURE".to_string(),
                "H-INWARD-CONTAINMENT".to_string(),
                "H-INWARD-RECOVERY".to_string(),
                "H-BOUNDED-OSCILLATORY".to_string(),
                "H-STRUCTURED-NOISY-TRAJECTORY".to_string(),
                "H-BASELINE-COMPATIBLE".to_string(),
            ],
            directional_incompatibility_exceptions: Vec::new(),
        },
        HeuristicBankEntry {
            heuristic_id: "H-CURVATURE-LED-DEPARTURE".to_string(),
            motif_label: "curvature-led admissibility departure candidate".to_string(),
            short_label: "curvature_departure".to_string(),
            scope_conditions: HeuristicScopeConditions {
                min_outward_drift_fraction: Some(0.65),
                max_outward_drift_fraction: None,
                min_inward_drift_fraction: None,
                max_inward_drift_fraction: Some(0.25),
                max_curvature_energy: None,
                min_curvature_energy: Some(4.0e-9),
                max_curvature_onset_score: None,
                min_curvature_onset_score: Some(0.40),
                min_directional_persistence: Some(0.60),
                min_sign_consistency: Some(0.60),
                min_channel_coherence: Some(0.50),
                min_aggregate_monotonicity: None,
                max_aggregate_monotonicity: None,
                min_slew_spike_count: None,
                max_slew_spike_count: Some(1),
                min_slew_spike_strength: None,
                max_slew_spike_strength: Some(0.01),
                min_boundary_grazing_episodes: None,
                max_boundary_grazing_episodes: None,
                min_boundary_recovery_count: None,
                min_coordinated_group_breach_fraction: None,
                max_coordinated_group_breach_fraction: Some(0.05),
                require_group_breach: false,
            },
            admissibility_requirements: AdmissibilityRequirement::ViolationRequired,
            regime_tags: vec![
                "fixed".to_string(),
                "widening".to_string(),
                "regime_shifted".to_string(),
            ],
            provenance: HeuristicProvenance {
                source: "typed heuristic bank".to_string(),
                note: "Illustrative mapping from slew-growth-dominated admissibility departure to a conservative transition-led departure motif.".to_string(),
            },
            applicability_note: "Use when admissibility departure is present and curvature growth is materially more salient than discrete-event spike structure. This remains a motif statement only.".to_string(),
            retrieval_priority: 82,
            compatible_with: vec!["H-MIXED-REGIME-TRANSITION".to_string()],
            incompatible_with: vec![
                "H-PERSISTENT-OUTWARD-DRIFT".to_string(),
                "H-PERSISTENT-ADMISSIBILITY-DEPARTURE".to_string(),
                "H-DISCRETE-EVENT".to_string(),
                "H-CURVATURE-RICH-TRANSITION".to_string(),
                "H-INWARD-CONTAINMENT".to_string(),
                "H-INWARD-RECOVERY".to_string(),
                "H-STRUCTURED-NOISY-TRAJECTORY".to_string(),
                "H-BOUNDED-OSCILLATORY".to_string(),
                "H-BASELINE-COMPATIBLE".to_string(),
            ],
            directional_incompatibility_exceptions: Vec::new(),
        },
        HeuristicBankEntry {
            heuristic_id: "H-MIXED-REGIME-TRANSITION".to_string(),
            motif_label: "mixed-regime transition candidate".to_string(),
            short_label: "mixed_regime_transition".to_string(),
            scope_conditions: HeuristicScopeConditions {
                min_outward_drift_fraction: Some(0.70),
                max_outward_drift_fraction: None,
                min_inward_drift_fraction: None,
                max_inward_drift_fraction: Some(0.20),
                max_curvature_energy: None,
                min_curvature_energy: Some(1.0e-7),
                max_curvature_onset_score: None,
                min_curvature_onset_score: Some(0.45),
                min_directional_persistence: Some(0.70),
                min_sign_consistency: Some(0.70),
                min_channel_coherence: Some(0.50),
                min_aggregate_monotonicity: Some(0.70),
                max_aggregate_monotonicity: None,
                min_slew_spike_count: Some(1),
                max_slew_spike_count: None,
                min_slew_spike_strength: Some(0.02),
                max_slew_spike_strength: None,
                min_boundary_grazing_episodes: None,
                max_boundary_grazing_episodes: None,
                min_boundary_recovery_count: None,
                min_coordinated_group_breach_fraction: None,
                max_coordinated_group_breach_fraction: Some(0.05),
                require_group_breach: false,
            },
            admissibility_requirements: AdmissibilityRequirement::ViolationRequired,
            regime_tags: vec!["regime_shifted".to_string()],
            provenance: HeuristicProvenance {
                source: "typed heuristic bank".to_string(),
                note: "Illustrative mapping from explicit regime-tag changes plus curvature-rich departure structure to a conservative mixed-regime transition motif.".to_string(),
            },
            applicability_note: "Use when the grammar record itself shows a regime shift and the departure remains curvature-led under breach. This is a contextual motif, not a unique causal recovery of the underlying transition.".to_string(),
            retrieval_priority: 81,
            compatible_with: vec![
                "H-CURVATURE-RICH-TRANSITION".to_string(),
                "H-CURVATURE-LED-DEPARTURE".to_string(),
            ],
            incompatible_with: vec![
                "H-PERSISTENT-OUTWARD-DRIFT".to_string(),
                "H-PERSISTENT-ADMISSIBILITY-DEPARTURE".to_string(),
                "H-INWARD-CONTAINMENT".to_string(),
                "H-INWARD-RECOVERY".to_string(),
                "H-BOUNDED-OSCILLATORY".to_string(),
                "H-STRUCTURED-NOISY-TRAJECTORY".to_string(),
                "H-BASELINE-COMPATIBLE".to_string(),
            ],
            directional_incompatibility_exceptions: Vec::new(),
        },
        HeuristicBankEntry {
            heuristic_id: "H-BOUNDARY-GRAZING".to_string(),
            motif_label: "near-boundary operation candidate".to_string(),
            short_label: "boundary_grazing".to_string(),
            scope_conditions: HeuristicScopeConditions {
                min_outward_drift_fraction: None,
                max_outward_drift_fraction: Some(0.70),
                min_inward_drift_fraction: None,
                max_inward_drift_fraction: None,
                max_curvature_energy: Some(0.050),
                min_curvature_energy: None,
                max_curvature_onset_score: Some(0.45),
                min_curvature_onset_score: None,
                min_directional_persistence: None,
                min_sign_consistency: None,
                min_channel_coherence: None,
                min_aggregate_monotonicity: None,
                max_aggregate_monotonicity: None,
                min_slew_spike_count: None,
                max_slew_spike_count: None,
                min_slew_spike_strength: None,
                max_slew_spike_strength: None,
                min_boundary_grazing_episodes: Some(2),
                max_boundary_grazing_episodes: None,
                min_boundary_recovery_count: Some(1),
                min_coordinated_group_breach_fraction: None,
                max_coordinated_group_breach_fraction: Some(0.05),
                require_group_breach: false,
            },
            admissibility_requirements: AdmissibilityRequirement::NoViolation,
            regime_tags: vec![
                "fixed".to_string(),
                "widening".to_string(),
                "tightening".to_string(),
                "regime_nominal".to_string(),
                "regime_shifted".to_string(),
            ],
            provenance: HeuristicProvenance {
                source: "typed heuristic bank".to_string(),
                note: "Illustrative mapping from repeated admissibility grazing without decisive breach to a near-boundary operating motif.".to_string(),
            },
            applicability_note: "Boundary grazing reflects operation relative to the configured envelope only. It is not a diagnosis of unsafe or failed hardware.".to_string(),
            retrieval_priority: 70,
            compatible_with: vec![
                "H-PERSISTENT-OUTWARD-DRIFT".to_string(),
                "H-COORDINATED-RISE".to_string(),
                "H-RECURRENT-BOUNDARY-RECURRENCE".to_string(),
            ],
            incompatible_with: vec![
                "H-PERSISTENT-ADMISSIBILITY-DEPARTURE".to_string(),
                "H-INWARD-CONTAINMENT".to_string(),
                "H-INWARD-RECOVERY".to_string(),
                "H-BASELINE-COMPATIBLE".to_string(),
            ],
            directional_incompatibility_exceptions: Vec::new(),
        },
        HeuristicBankEntry {
            heuristic_id: "H-RECURRENT-BOUNDARY-RECURRENCE".to_string(),
            motif_label: "recurrent boundary operation candidate".to_string(),
            short_label: "recurrent_boundary".to_string(),
            scope_conditions: HeuristicScopeConditions {
                min_outward_drift_fraction: None,
                max_outward_drift_fraction: Some(0.75),
                min_inward_drift_fraction: None,
                max_inward_drift_fraction: None,
                max_curvature_energy: Some(0.020),
                min_curvature_energy: None,
                max_curvature_onset_score: Some(0.35),
                min_curvature_onset_score: None,
                min_directional_persistence: None,
                min_sign_consistency: None,
                min_channel_coherence: None,
                min_aggregate_monotonicity: None,
                max_aggregate_monotonicity: None,
                min_slew_spike_count: None,
                max_slew_spike_count: Some(1),
                min_slew_spike_strength: None,
                max_slew_spike_strength: Some(0.02),
                min_boundary_grazing_episodes: Some(3),
                max_boundary_grazing_episodes: None,
                min_boundary_recovery_count: Some(2),
                min_coordinated_group_breach_fraction: None,
                max_coordinated_group_breach_fraction: Some(0.05),
                require_group_breach: false,
            },
            admissibility_requirements: AdmissibilityRequirement::NoViolation,
            regime_tags: vec![
                "fixed".to_string(),
                "widening".to_string(),
                "tightening".to_string(),
                "regime_nominal".to_string(),
                "regime_shifted".to_string(),
            ],
            provenance: HeuristicProvenance {
                source: "typed heuristic bank".to_string(),
                note: "Illustrative mapping from repeated admissibility-boundary returns without decisive breach to a conservative recurrent-boundary motif.".to_string(),
            },
            applicability_note: "Use when boundary interaction is recurrent and recoverable under the configured envelope. This remains an operating-pattern motif only.".to_string(),
            retrieval_priority: 71,
            compatible_with: vec!["H-BOUNDARY-GRAZING".to_string()],
            incompatible_with: vec![
                "H-PERSISTENT-ADMISSIBILITY-DEPARTURE".to_string(),
                "H-INWARD-CONTAINMENT".to_string(),
                "H-INWARD-RECOVERY".to_string(),
                "H-BASELINE-COMPATIBLE".to_string(),
            ],
            directional_incompatibility_exceptions: Vec::new(),
        },
        HeuristicBankEntry {
            heuristic_id: "H-COORDINATED-RISE".to_string(),
            motif_label: "correlated degradation or common-mode disturbance candidate".to_string(),
            short_label: "coordinated_rise".to_string(),
            scope_conditions: HeuristicScopeConditions {
                min_outward_drift_fraction: Some(0.45),
                max_outward_drift_fraction: None,
                min_inward_drift_fraction: None,
                max_inward_drift_fraction: None,
                max_curvature_energy: None,
                min_curvature_energy: None,
                max_curvature_onset_score: Some(0.40),
                min_curvature_onset_score: None,
                min_directional_persistence: Some(0.45),
                min_sign_consistency: Some(0.45),
                min_channel_coherence: Some(0.55),
                min_aggregate_monotonicity: Some(0.45),
                max_aggregate_monotonicity: None,
                min_slew_spike_count: None,
                max_slew_spike_count: None,
                min_slew_spike_strength: None,
                max_slew_spike_strength: None,
                min_boundary_grazing_episodes: None,
                max_boundary_grazing_episodes: None,
                min_boundary_recovery_count: None,
                min_coordinated_group_breach_fraction: None,
                max_coordinated_group_breach_fraction: None,
                require_group_breach: true,
            },
            admissibility_requirements: AdmissibilityRequirement::Any,
            regime_tags: vec!["aggregate".to_string()],
            provenance: HeuristicProvenance {
                source: "typed heuristic bank".to_string(),
                note: "Illustrative mapping from coordinated envelope-relative rise across grouped residuals to a common-mode motif.".to_string(),
            },
            applicability_note: "Use only for grouped residual structures with explicit aggregate envelopes. It does not identify the shared latent cause uniquely.".to_string(),
            retrieval_priority: 88,
            compatible_with: vec![
                "H-PERSISTENT-OUTWARD-DRIFT".to_string(),
                "H-BOUNDARY-GRAZING".to_string(),
                "H-COORDINATED-DEPARTURE".to_string(),
            ],
            incompatible_with: vec![
                "H-PERSISTENT-ADMISSIBILITY-DEPARTURE".to_string(),
                "H-INWARD-CONTAINMENT".to_string(),
                "H-INWARD-RECOVERY".to_string(),
                "H-BASELINE-COMPATIBLE".to_string(),
            ],
            directional_incompatibility_exceptions: Vec::new(),
        },
        HeuristicBankEntry {
            heuristic_id: "H-COORDINATED-DEPARTURE".to_string(),
            motif_label: "coordinated admissibility departure candidate".to_string(),
            short_label: "coordinated_departure".to_string(),
            scope_conditions: HeuristicScopeConditions {
                min_outward_drift_fraction: Some(0.55),
                max_outward_drift_fraction: None,
                min_inward_drift_fraction: None,
                max_inward_drift_fraction: Some(0.25),
                max_curvature_energy: None,
                min_curvature_energy: None,
                max_curvature_onset_score: Some(0.35),
                min_curvature_onset_score: None,
                min_directional_persistence: Some(0.55),
                min_sign_consistency: Some(0.55),
                min_channel_coherence: Some(0.60),
                min_aggregate_monotonicity: Some(0.55),
                max_aggregate_monotonicity: None,
                min_slew_spike_count: None,
                max_slew_spike_count: None,
                min_slew_spike_strength: None,
                max_slew_spike_strength: None,
                min_boundary_grazing_episodes: None,
                max_boundary_grazing_episodes: None,
                min_boundary_recovery_count: None,
                min_coordinated_group_breach_fraction: Some(0.30),
                max_coordinated_group_breach_fraction: None,
                require_group_breach: true,
            },
            admissibility_requirements: AdmissibilityRequirement::ViolationRequired,
            regime_tags: vec!["aggregate".to_string()],
            provenance: HeuristicProvenance {
                source: "typed heuristic bank".to_string(),
                note: "Illustrative mapping from coordinated grouped breach with actual admissibility departure to a conservative common-mode departure motif.".to_string(),
            },
            applicability_note: "Use only when grouped residual structure is configured and the aggregate envelope is materially breached. It remains a common-mode compatibility statement, not a unique cause claim.".to_string(),
            retrieval_priority: 87,
            compatible_with: vec!["H-COORDINATED-RISE".to_string()],
            incompatible_with: vec![
                "H-INWARD-CONTAINMENT".to_string(),
                "H-BASELINE-COMPATIBLE".to_string(),
            ],
            directional_incompatibility_exceptions: Vec::new(),
        },
        HeuristicBankEntry {
            heuristic_id: "H-INWARD-CONTAINMENT".to_string(),
            motif_label: "inward-compatible containment candidate".to_string(),
            short_label: "inward_containment".to_string(),
            scope_conditions: HeuristicScopeConditions {
                min_outward_drift_fraction: None,
                max_outward_drift_fraction: Some(0.35),
                min_inward_drift_fraction: Some(0.55),
                max_inward_drift_fraction: None,
                max_curvature_energy: Some(0.020),
                min_curvature_energy: None,
                max_curvature_onset_score: Some(0.25),
                min_curvature_onset_score: None,
                min_directional_persistence: Some(0.55),
                min_sign_consistency: Some(0.55),
                min_channel_coherence: Some(0.45),
                min_aggregate_monotonicity: None,
                max_aggregate_monotonicity: None,
                min_slew_spike_count: None,
                max_slew_spike_count: None,
                min_slew_spike_strength: None,
                max_slew_spike_strength: None,
                min_boundary_grazing_episodes: None,
                max_boundary_grazing_episodes: None,
                min_boundary_recovery_count: None,
                min_coordinated_group_breach_fraction: None,
                max_coordinated_group_breach_fraction: Some(0.05),
                require_group_breach: false,
            },
            admissibility_requirements: AdmissibilityRequirement::NoViolation,
            regime_tags: vec![
                "fixed".to_string(),
                "tightening".to_string(),
                "regime_nominal".to_string(),
            ],
            provenance: HeuristicProvenance {
                source: "typed heuristic bank".to_string(),
                note: "Illustrative mapping from persistent inward-compatible evolution to a containment or recovery-style motif.".to_string(),
            },
            applicability_note: "This motif is admissibility-relative and does not assert underlying recovery physics.".to_string(),
            retrieval_priority: 75,
            compatible_with: vec!["H-INWARD-RECOVERY".to_string()],
            incompatible_with: vec![
                "H-PERSISTENT-OUTWARD-DRIFT".to_string(),
                "H-DISCRETE-EVENT".to_string(),
                "H-CURVATURE-RICH-TRANSITION".to_string(),
                "H-CURVATURE-LED-DEPARTURE".to_string(),
                "H-BOUNDARY-GRAZING".to_string(),
                "H-COORDINATED-RISE".to_string(),
                "H-PERSISTENT-ADMISSIBILITY-DEPARTURE".to_string(),
                "H-MIXED-REGIME-TRANSITION".to_string(),
                "H-RECURRENT-BOUNDARY-RECURRENCE".to_string(),
                "H-COORDINATED-DEPARTURE".to_string(),
                "H-STRUCTURED-NOISY-TRAJECTORY".to_string(),
                "H-BOUNDED-OSCILLATORY".to_string(),
                "H-BASELINE-COMPATIBLE".to_string(),
            ],
            directional_incompatibility_exceptions: Vec::new(),
        },
        HeuristicBankEntry {
            heuristic_id: "H-INWARD-RECOVERY".to_string(),
            motif_label: "inward recovery-compatible candidate".to_string(),
            short_label: "inward_recovery".to_string(),
            scope_conditions: HeuristicScopeConditions {
                min_outward_drift_fraction: None,
                max_outward_drift_fraction: Some(0.30),
                min_inward_drift_fraction: Some(0.75),
                max_inward_drift_fraction: None,
                max_curvature_energy: Some(0.010),
                min_curvature_energy: None,
                max_curvature_onset_score: Some(0.30),
                min_curvature_onset_score: None,
                min_directional_persistence: Some(0.70),
                min_sign_consistency: Some(0.65),
                min_channel_coherence: Some(0.45),
                min_aggregate_monotonicity: None,
                max_aggregate_monotonicity: None,
                min_slew_spike_count: None,
                max_slew_spike_count: None,
                min_slew_spike_strength: None,
                max_slew_spike_strength: None,
                min_boundary_grazing_episodes: None,
                max_boundary_grazing_episodes: None,
                min_boundary_recovery_count: Some(2),
                min_coordinated_group_breach_fraction: None,
                max_coordinated_group_breach_fraction: Some(0.05),
                require_group_breach: false,
            },
            admissibility_requirements: AdmissibilityRequirement::NoViolation,
            regime_tags: vec![
                "tightening".to_string(),
                "regime_nominal".to_string(),
                "fixed".to_string(),
            ],
            provenance: HeuristicProvenance {
                source: "typed heuristic bank".to_string(),
                note: "Illustrative mapping from repeated returns to admissibility under inward-compatible evolution to a conservative recovery-compatible motif.".to_string(),
            },
            applicability_note: "Use when inward-compatible motion is accompanied by repeated returns to admissibility under the configured envelope. This remains envelope-relative and non-causal.".to_string(),
            retrieval_priority: 74,
            compatible_with: vec!["H-INWARD-CONTAINMENT".to_string()],
            incompatible_with: vec![
                "H-PERSISTENT-OUTWARD-DRIFT".to_string(),
                "H-PERSISTENT-ADMISSIBILITY-DEPARTURE".to_string(),
                "H-DISCRETE-EVENT".to_string(),
                "H-CURVATURE-RICH-TRANSITION".to_string(),
                "H-CURVATURE-LED-DEPARTURE".to_string(),
                "H-BOUNDARY-GRAZING".to_string(),
                "H-RECURRENT-BOUNDARY-RECURRENCE".to_string(),
                "H-COORDINATED-RISE".to_string(),
                "H-MIXED-REGIME-TRANSITION".to_string(),
                "H-STRUCTURED-NOISY-TRAJECTORY".to_string(),
                "H-BASELINE-COMPATIBLE".to_string(),
            ],
            directional_incompatibility_exceptions: Vec::new(),
        },
        HeuristicBankEntry {
            heuristic_id: "H-BOUNDED-OSCILLATORY".to_string(),
            motif_label: "bounded oscillatory operation candidate".to_string(),
            short_label: "bounded_oscillatory".to_string(),
            scope_conditions: HeuristicScopeConditions {
                min_outward_drift_fraction: None,
                max_outward_drift_fraction: Some(0.60),
                min_inward_drift_fraction: Some(0.35),
                max_inward_drift_fraction: Some(0.60),
                max_curvature_energy: Some(1.0e-3),
                min_curvature_energy: Some(1.0e-6),
                max_curvature_onset_score: Some(0.20),
                min_curvature_onset_score: None,
                min_directional_persistence: Some(0.75),
                min_sign_consistency: Some(0.50),
                min_channel_coherence: Some(0.45),
                min_aggregate_monotonicity: None,
                max_aggregate_monotonicity: Some(0.12),
                min_slew_spike_count: Some(2),
                max_slew_spike_count: None,
                min_slew_spike_strength: None,
                max_slew_spike_strength: Some(0.01),
                min_boundary_grazing_episodes: None,
                max_boundary_grazing_episodes: Some(0),
                min_boundary_recovery_count: None,
                min_coordinated_group_breach_fraction: None,
                max_coordinated_group_breach_fraction: Some(0.0),
                require_group_breach: false,
            },
            admissibility_requirements: AdmissibilityRequirement::NoViolation,
            regime_tags: vec![
                "fixed".to_string(),
                "tightening".to_string(),
                "widening".to_string(),
                "regime_nominal".to_string(),
            ],
            provenance: HeuristicProvenance {
                source: "typed heuristic bank".to_string(),
                note: "Illustrative mapping from balanced outward/inward evolution with modest bounded slew activity to a conservative oscillatory motif.".to_string(),
            },
            applicability_note: "This motif stays envelope-relative and descriptive. It indicates bounded oscillatory structure under the configured model, not a unique source of periodicity.".to_string(),
            retrieval_priority: 66,
            compatible_with: Vec::new(),
            incompatible_with: vec![
                "H-PERSISTENT-OUTWARD-DRIFT".to_string(),
                "H-PERSISTENT-ADMISSIBILITY-DEPARTURE".to_string(),
                "H-DISCRETE-EVENT".to_string(),
                "H-CURVATURE-RICH-TRANSITION".to_string(),
                "H-CURVATURE-LED-DEPARTURE".to_string(),
                "H-MIXED-REGIME-TRANSITION".to_string(),
                "H-INWARD-CONTAINMENT".to_string(),
                "H-STRUCTURED-NOISY-TRAJECTORY".to_string(),
                "H-BASELINE-COMPATIBLE".to_string(),
            ],
            directional_incompatibility_exceptions: Vec::new(),
        },
        HeuristicBankEntry {
            heuristic_id: "H-STRUCTURED-NOISY-TRAJECTORY".to_string(),
            motif_label: "structured noisy trajectory candidate".to_string(),
            short_label: "structured_noisy".to_string(),
            scope_conditions: HeuristicScopeConditions {
                min_outward_drift_fraction: None,
                max_outward_drift_fraction: Some(0.65),
                min_inward_drift_fraction: Some(0.35),
                max_inward_drift_fraction: Some(0.60),
                max_curvature_energy: Some(0.010),
                min_curvature_energy: Some(5.0e-4),
                max_curvature_onset_score: Some(0.35),
                min_curvature_onset_score: Some(0.15),
                min_directional_persistence: Some(0.45),
                min_sign_consistency: Some(0.50),
                min_channel_coherence: Some(0.45),
                min_aggregate_monotonicity: None,
                max_aggregate_monotonicity: Some(0.25),
                min_slew_spike_count: Some(8),
                max_slew_spike_count: None,
                min_slew_spike_strength: None,
                max_slew_spike_strength: Some(0.02),
                min_boundary_grazing_episodes: None,
                max_boundary_grazing_episodes: Some(0),
                min_boundary_recovery_count: None,
                min_coordinated_group_breach_fraction: None,
                max_coordinated_group_breach_fraction: Some(0.0),
                require_group_breach: false,
            },
            admissibility_requirements: AdmissibilityRequirement::NoViolation,
            regime_tags: vec![
                "fixed".to_string(),
                "widening".to_string(),
                "tightening".to_string(),
            ],
            provenance: HeuristicProvenance {
                source: "typed heuristic bank".to_string(),
                note: "Illustrative mapping from bounded but visibly structured residual agitation to a conservative structured-noise motif.".to_string(),
            },
            applicability_note: "Use when many modest slew excursions remain admissible and weakly directional under the configured model. This motif describes observed structure only; it does not identify a disturbance source uniquely.".to_string(),
            retrieval_priority: 67,
            compatible_with: Vec::new(),
            incompatible_with: vec![
                "H-PERSISTENT-OUTWARD-DRIFT".to_string(),
                "H-PERSISTENT-ADMISSIBILITY-DEPARTURE".to_string(),
                "H-DISCRETE-EVENT".to_string(),
                "H-CURVATURE-RICH-TRANSITION".to_string(),
                "H-CURVATURE-LED-DEPARTURE".to_string(),
                "H-MIXED-REGIME-TRANSITION".to_string(),
                "H-INWARD-CONTAINMENT".to_string(),
                "H-INWARD-RECOVERY".to_string(),
                "H-BOUNDED-OSCILLATORY".to_string(),
                "H-BASELINE-COMPATIBLE".to_string(),
            ],
            directional_incompatibility_exceptions: Vec::new(),
        },
        HeuristicBankEntry {
            heuristic_id: "H-BASELINE-COMPATIBLE".to_string(),
            motif_label: "weakly structured baseline-compatible observation candidate".to_string(),
            short_label: "baseline_compatible".to_string(),
            scope_conditions: HeuristicScopeConditions {
                min_outward_drift_fraction: None,
                max_outward_drift_fraction: Some(0.53),
                min_inward_drift_fraction: Some(0.40),
                max_inward_drift_fraction: Some(0.60),
                max_curvature_energy: Some(1.0e-5),
                min_curvature_energy: None,
                max_curvature_onset_score: Some(0.20),
                min_curvature_onset_score: None,
                min_directional_persistence: None,
                min_sign_consistency: None,
                min_channel_coherence: None,
                min_aggregate_monotonicity: None,
                max_aggregate_monotonicity: Some(0.08),
                min_slew_spike_count: None,
                max_slew_spike_count: Some(1),
                min_slew_spike_strength: None,
                max_slew_spike_strength: Some(1.0e-3),
                min_boundary_grazing_episodes: None,
                max_boundary_grazing_episodes: Some(0),
                min_boundary_recovery_count: None,
                min_coordinated_group_breach_fraction: None,
                max_coordinated_group_breach_fraction: Some(0.0),
                require_group_breach: false,
            },
            admissibility_requirements: AdmissibilityRequirement::NoViolation,
            regime_tags: vec![
                "fixed".to_string(),
                "tightening".to_string(),
                "widening".to_string(),
                "regime_nominal".to_string(),
            ],
            provenance: HeuristicProvenance {
                source: "typed heuristic bank".to_string(),
                note: "Illustrative mapping from low-structure, admissible residual evolution to a conservative baseline-compatible observation motif.".to_string(),
            },
            applicability_note: "Use only as a low-commitment statement relative to the configured prediction and envelope. It is not a validated health or nominality classifier.".to_string(),
            retrieval_priority: 60,
            compatible_with: Vec::new(),
            incompatible_with: vec![
                "H-PERSISTENT-OUTWARD-DRIFT".to_string(),
                "H-PERSISTENT-ADMISSIBILITY-DEPARTURE".to_string(),
                "H-DISCRETE-EVENT".to_string(),
                "H-CURVATURE-RICH-TRANSITION".to_string(),
                "H-CURVATURE-LED-DEPARTURE".to_string(),
                "H-BOUNDARY-GRAZING".to_string(),
                "H-COORDINATED-RISE".to_string(),
                "H-INWARD-CONTAINMENT".to_string(),
                "H-BOUNDED-OSCILLATORY".to_string(),
                "H-MIXED-REGIME-TRANSITION".to_string(),
                "H-RECURRENT-BOUNDARY-RECURRENCE".to_string(),
                "H-COORDINATED-DEPARTURE".to_string(),
                "H-INWARD-RECOVERY".to_string(),
                "H-STRUCTURED-NOISY-TRAJECTORY".to_string(),
            ],
            directional_incompatibility_exceptions: Vec::new(),
        },
    ]
}
