//! The seeded soft-sensor dataset catalogue.
//!
//! Each record is a *public* dataset where cheap sensors infer a hard-to-measure target, sourced and
//! access-flagged. Dataset bytes are NOT vendored. `implementation_status` is `Catalogued` for all
//! entries at this stage: the corpus sources the datasets; deterministic-witness *demonstrators* on
//! them are flipped to `Executed` as they land. Cheap-sensor entries (`cheap_sensor: true`) are the
//! DSFB thesis; the spectroscopy-input entries are flagged `false` and kept for contrast.
//!
//! Every record also carries four hash-sealed provenance classification tiers (added P53): a
//! `license_confidence`, `access_confidence`, `redistribution_policy`, and `source_authority`
//! (see [`crate::types`]). These are honest, per-record disclosure derived from the cited `license`
//! string + `url` host + venue — confidence/policy statements, never legal opinions or quality claims.
//! Each inline `//` note above a record's classification records the reasoning so the tier is auditable.

use crate::types::{
    AccessConfidence as AC, AccessStatus as A, ImplementationStatus::Catalogued,
    LicenseConfidence as LC, ProcessDomain as D, RedistributionPolicy as RP,
    SoftSensorDatasetRecordV1, SourceAuthorityKind as SA, SourceRef, TargetKind as T,
};

/// Public soft-sensor datasets (cheap sensors -> hard-to-measure target).
///
/// **To add a dataset:** append a record filling every field per the `SoftSensorDatasetRecordV1` doc in
/// `types.rs`; set the four provenance axes (`license_confidence` / `access_confidence` /
/// `redistribution_policy` / `source_authority`) honestly from the upstream terms; keep `redistributed: false`
/// (this crate ships no bytes); then re-mint `corpus_hash_v1` as a *governed* re-freeze (the gate test in
/// `tests/corpus_gates.rs` pins the old hash and fails until you update it deliberately).
pub const SOFT_SENSOR_DATASETS: &[SoftSensorDatasetRecordV1] = &[
    SoftSensorDatasetRecordV1 {
        dataset_id: "sru",
        name: "Sulfur Recovery Unit (SRU)",
        domain: D::RefineryDistillation,
        cheap_sensors: &["acid-gas flow", "MEA-gas flow", "SWS-zone air flow", "main-zone air flows"],
        n_cheap_inputs: 5,
        cheap_sensor: true,
        target: "H2S and SO2 concentration in tail gas",
        target_kind: T::Concentration,
        target_measurement: "online gas analyzers that foul/drift and are taken offline for servicing",
        has_fault_labels: false,
        input_target_lag: "output delayed vs inputs; canonical preprocessing augments lagged input windows",
        sampling: "~10,081 samples at 1-minute cadence",
        deterministic_inference: "drift/slew grammar + admissibility envelope on the 5 flow residuals; documented flow->composition relationship admitted as a ProcessStructure witness, not a probabilistic regression",
        access: A::OpenDownload,
        redistributed: false,
        implementation_status: Catalogued,
        // Springer-monograph benchmark on a community GitHub mirror; no explicit licence on the mirror.
        license_confidence: LC::ResearchUseCustomary,
        access_confidence: AC::OpenMirrorUnverified,
        redistribution_policy: RP::UpstreamVerifyBeforeRedistribution,
        source_authority: SA::AuthorOrVendorHost,
        source: SourceRef { citation_key: "fortuna2007soft", authors: "Fortuna, Graziani, Rizzo, Xibilia", year: 2007, venue_or_source: "Springer monograph; ERG/ISAB refinery, Italy", url: "https://github.com/softsensors/soft-sensor-data", license: "research-use; no explicit licence on mirror" },
    },
    SoftSensorDatasetRecordV1 {
        dataset_id: "debutanizer",
        name: "Debutanizer column",
        domain: D::RefineryDistillation,
        cheap_sensors: &["top temperature", "top pressure", "reflux flow", "flow to next process", "6th-tray temperature", "two bottom temperatures"],
        n_cheap_inputs: 7,
        cheap_sensor: true,
        target: "butane (C4) content in column bottoms",
        target_kind: T::Composition,
        target_measurement: "lab/online gas chromatograph",
        has_fault_labels: false,
        input_target_lag: "significant dead time; canonical preprocessing shifts the target by ~8 samples",
        sampling: "2,394 samples",
        deterministic_inference: "the ~8-sample lag is a documented transport delay; deterministic lagged-residual grammar, no learned weights",
        access: A::OpenDownload,
        redistributed: false,
        implementation_status: Catalogued,
        // Same Springer-monograph mirror as SRU; research-use, no explicit licence on the mirror.
        license_confidence: LC::ResearchUseCustomary,
        access_confidence: AC::OpenMirrorUnverified,
        redistribution_policy: RP::UpstreamVerifyBeforeRedistribution,
        source_authority: SA::AuthorOrVendorHost,
        source: SourceRef { citation_key: "fortuna2007soft", authors: "Fortuna et al.; refinery in Sicily, Italy", year: 2007, venue_or_source: "Springer monograph", url: "https://github.com/softsensors/soft-sensor-data", license: "research-use; no explicit licence on mirror" },
    },
    SoftSensorDatasetRecordV1 {
        dataset_id: "tep",
        name: "Tennessee Eastman Process",
        domain: D::GeneralProcess,
        cheap_sensors: &["reactor/separator/stripper temperatures", "pressures", "levels", "feed/product flows", "compressor work", "11 manipulated valves"],
        n_cheap_inputs: 22,
        cheap_sensor: true,
        target: "stream compositions / product quality (analyzer channels)",
        target_kind: T::Composition,
        target_measurement: "composition analyzers sampling every 6 / 15 min (multi-rate)",
        has_fault_labels: true,
        input_target_lag: "analyzers lag the continuous sensors (6/15-min multi-rate)",
        sampling: "3-min sampling; Rieth set = 500 runs/fault",
        deterministic_inference: "the project already runs the deterministic residual grammar + control-action context on TEP; composition soft-sensing would key on the documented multi-rate relationship",
        access: A::OpenDownload,
        redistributed: false,
        implementation_status: Catalogued,
        // CC0 on Harvard Dataverse with a persistent DOI — fully open, immutable provenance.
        license_confidence: LC::ExplicitOpen,
        access_confidence: AC::OpenConfirmed,
        redistribution_policy: RP::UpstreamPermitsAttribution,
        source_authority: SA::DoiArchive,
        source: SourceRef { citation_key: "rieth2017tep", authors: "Downs & Vogel; Rieth et al.", year: 2017, venue_or_source: "Harvard Dataverse", url: "https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/6C3JR1", license: "CC0" },
    },
    SoftSensorDatasetRecordV1 {
        dataset_id: "mining_flotation",
        name: "Quality Prediction in a Mining Process (froth flotation)",
        domain: D::MineralProcessing,
        cheap_sensors: &["% iron/silica feed", "starch flow", "amina flow", "ore-pulp flow/pH/density", "air-flow + level for 7 flotation columns"],
        n_cheap_inputs: 21,
        cheap_sensor: true,
        target: "% silica concentrate (impurity); % iron concentrate",
        target_kind: T::Quality,
        target_measurement: "hourly lab assay (slow, costly chemical analysis)",
        has_fault_labels: false,
        input_target_lag: "process at 20 s, assay hourly: 1-hour target lag vs 20-s process data",
        sampling: "737,453 rows, 24 cols, Mar-Sep 2017",
        deterministic_inference: "deterministic envelope + drift grammar on flotation residuals for early silica-excursion warning; provenance-sealed locally (research drop)",
        access: A::KaggleAccount,
        redistributed: false,
        implementation_status: Catalogued,
        // Kaggle community upload; page says "public" but exact terms need verification.
        license_confidence: LC::StatedNeedsVerification,
        access_confidence: AC::AccountRequired,
        redistribution_policy: RP::UpstreamVerifyBeforeRedistribution,
        source_authority: SA::CommunityUpload,
        source: SourceRef { citation_key: "magalhaes2017mining", authors: "Eduardo Magalhaes (real flotation plant)", year: 2017, venue_or_source: "Kaggle", url: "https://www.kaggle.com/datasets/edumagalhaes/quality-prediction-in-a-mining-process", license: "public (verify exact terms on page)" },
    },
    SoftSensorDatasetRecordV1 {
        dataset_id: "ccpp",
        name: "Combined Cycle Power Plant",
        domain: D::Power,
        cheap_sensors: &["ambient temperature", "ambient pressure", "relative humidity", "exhaust vacuum"],
        n_cheap_inputs: 4,
        cheap_sensor: true,
        target: "net hourly electrical energy output (MW)",
        target_kind: T::Energy,
        target_measurement: "metered output (performance target)",
        has_fault_labels: false,
        input_target_lag: "none (hourly averages aligned)",
        sampling: "9,568 hourly points, 2006-2011",
        deterministic_inference: "deterministic envelope on the 4 ambient residuals vs documented performance map; no probabilistic regression",
        access: A::OpenDownload,
        redistributed: false,
        implementation_status: Catalogued,
        // CC BY 4.0 on the UCI ML Repository (stable dataset ID).
        license_confidence: LC::ExplicitOpen,
        access_confidence: AC::OpenConfirmed,
        redistribution_policy: RP::UpstreamPermitsAttribution,
        source_authority: SA::CuratedMlRepository,
        source: SourceRef { citation_key: "tufekci2014ccpp", authors: "Tufekci, Kaya", year: 2014, venue_or_source: "UCI ML Repository #294", url: "https://archive.ics.uci.edu/dataset/294/combined+cycle+power+plant", license: "CC BY 4.0" },
    },
    SoftSensorDatasetRecordV1 {
        dataset_id: "gas_turbine_emissions",
        name: "Gas Turbine CO and NOx Emission",
        domain: D::Emissions,
        cheap_sensors: &["ambient T/P/humidity", "air-filter difference pressure", "exhaust pressure", "turbine inlet/after temperatures", "compressor discharge pressure", "energy yield"],
        n_cheap_inputs: 9,
        cheap_sensor: true,
        target: "CO and NOx (mg/m^3)",
        target_kind: T::Emissions,
        target_measurement: "continuous emissions monitoring system (CEMS) analyzer",
        has_fault_labels: false,
        input_target_lag: "hourly-aggregated, aligned",
        sampling: "36,733 hourly rows, 2011-2015",
        deterministic_inference: "predictive-emissions (PEMS) target; deterministic envelope/drift grammar on the 9 process residuals",
        access: A::OpenDownload,
        redistributed: false,
        implementation_status: Catalogued,
        // CC BY 4.0 on the UCI ML Repository (stable dataset ID).
        license_confidence: LC::ExplicitOpen,
        access_confidence: AC::OpenConfirmed,
        redistribution_policy: RP::UpstreamPermitsAttribution,
        source_authority: SA::CuratedMlRepository,
        source: SourceRef { citation_key: "kaya2019gasturbine", authors: "Kaya, Tufekci, Uzun", year: 2019, venue_or_source: "UCI ML Repository #551", url: "https://archive.ics.uci.edu/dataset/551/gas+turbine+co+and+nox+emission+data+set", license: "CC BY 4.0" },
    },
    SoftSensorDatasetRecordV1 {
        dataset_id: "steel_energy",
        name: "Steel Industry Energy Consumption",
        domain: D::Power,
        cheap_sensors: &["lagging/leading reactive power", "lagging/leading power factor", "load type", "time-of-day"],
        n_cheap_inputs: 6,
        cheap_sensor: true,
        target: "CO2 emission (tCO2) and energy usage (kWh)",
        target_kind: T::Emissions,
        target_measurement: "metering / emissions accounting",
        has_fault_labels: false,
        input_target_lag: "hourly, aligned",
        sampling: "hourly, one year (DAEWOO Steel, S. Korea)",
        deterministic_inference: "deterministic relationship from power signals to emission; envelope grammar on power residuals",
        access: A::OpenDownload,
        redistributed: false,
        implementation_status: Catalogued,
        // CC BY 4.0 on the UCI ML Repository (stable dataset ID).
        license_confidence: LC::ExplicitOpen,
        access_confidence: AC::OpenConfirmed,
        redistribution_policy: RP::UpstreamPermitsAttribution,
        source_authority: SA::CuratedMlRepository,
        source: SourceRef { citation_key: "ve2021steel", authors: "V.E., Cho (DAEWOO Steel)", year: 2021, venue_or_source: "UCI ML Repository #851", url: "https://archive.ics.uci.edu/dataset/851/steel+industry+energy+consumption", license: "CC BY 4.0" },
    },
    SoftSensorDatasetRecordV1 {
        dataset_id: "uci_water_treatment",
        name: "UCI Water Treatment Plant",
        domain: D::Wastewater,
        cheap_sensors: &["flows", "pH", "conductivity", "suspended solids", "COD/BOD", "sediments across inlet/pre/bio/outlet"],
        n_cheap_inputs: 38,
        cheap_sensor: true,
        target: "operational state / removal efficiency (8 quality + 9 performance %)",
        target_kind: T::RemovalEfficiency,
        target_measurement: "daily lab sampling",
        has_fault_labels: true,
        input_target_lag: "daily cadence; settler effects span hours",
        sampling: "527 days, 1990-91 (Spain)",
        deterministic_inference: "deterministic state classification from daily residuals; note: only one flow column limits a rigorous mass balance",
        access: A::OpenDownload,
        redistributed: false,
        implementation_status: Catalogued,
        // CC BY 4.0 on the UCI ML Repository (stable dataset ID).
        license_confidence: LC::ExplicitOpen,
        access_confidence: AC::OpenConfirmed,
        redistribution_policy: RP::UpstreamPermitsAttribution,
        source_authority: SA::CuratedMlRepository,
        source: SourceRef { citation_key: "bejar1991wtp", authors: "Bejar, Cortes, Poch", year: 1991, venue_or_source: "UCI ML Repository #106", url: "https://archive.ics.uci.edu/dataset/106/water+treatment+plant", license: "CC BY 4.0" },
    },
    SoftSensorDatasetRecordV1 {
        dataset_id: "bsm1",
        name: "Benchmark Simulation Model No. 1 (BSM1)",
        domain: D::Wastewater,
        cheap_sensors: &["dissolved oxygen", "flow", "NH4", "NO3 across a 5-compartment ASM1 reactor + clarifier"],
        n_cheap_inputs: 8,
        cheap_sensor: true,
        target: "effluent quality (ammonia, total N, COD, BOD, TSS; Effluent Quality Index)",
        target_kind: T::RemovalEfficiency,
        target_measurement: "lab sampling of effluent composition",
        has_fault_labels: false,
        input_target_lag: "process-rate; effluent integrates upstream dynamics",
        sampling: "simulation (generate by running the IWA code)",
        deterministic_inference: "ASM1 component mass balances are documented; closeable balance witnesses possible from the generated streams",
        access: A::CodeGeneratesData,
        redistributed: false,
        implementation_status: Catalogued,
        // Open-academic IWA reference model on GitHub; you run the code to generate the data.
        license_confidence: LC::ResearchUseCustomary,
        access_confidence: AC::GeneratedByCode,
        redistribution_policy: RP::UpstreamVerifyBeforeRedistribution,
        source_authority: SA::SimulatorCodebase,
        source: SourceRef { citation_key: "alex2008benchmark", authors: "IWA Benchmarking Task Group", year: 2008, venue_or_source: "IWA / GitHub wwtmodels", url: "https://github.com/wwtmodels/Benchmark-Simulation-Models", license: "open academic (IWA)" },
    },
    SoftSensorDatasetRecordV1 {
        dataset_id: "wwtp_n2o",
        name: "Full-scale WWTP N2O time series",
        domain: D::Wastewater,
        cheap_sensors: &["influent/effluent bio-chemical params", "operational + environmental factors"],
        n_cheap_inputs: 12,
        cheap_sensor: true,
        target: "nitrous oxide (N2O) concentration",
        target_kind: T::Emissions,
        target_measurement: "dedicated N2O analyzer (expensive); soft sensor from operational data",
        has_fault_labels: false,
        input_target_lag: "2-min resolution; biological lags",
        sampling: "2-min, 2 years, full-scale plant",
        deterministic_inference: "deterministic drift/envelope grammar on operational residuals; documented nitrification/denitrification coupling",
        access: A::OpenDownload,
        redistributed: false,
        implementation_status: Catalogued,
        // arXiv data-in-brief + a linked repository; licence must be verified in the paper.
        license_confidence: LC::StatedNeedsVerification,
        access_confidence: AC::OpenMirrorUnverified,
        redistribution_policy: RP::UpstreamVerifyBeforeRedistribution,
        source_authority: SA::AuthorOrVendorHost,
        source: SourceRef { citation_key: "wwtp_n2o_2024", authors: "(data-in-brief, arXiv 2407.05959)", year: 2024, venue_or_source: "arXiv + linked repository", url: "https://arxiv.org/abs/2407.05959", license: "verify in paper" },
    },
    SoftSensorDatasetRecordV1 {
        dataset_id: "pulp_kappa",
        name: "Pulp digester Kappa number (pulplignin)",
        domain: D::PulpPaper,
        cheap_sensors: &["effective alkali", "temperatures", "flows", "dissolved-lignin proxies (several columns hour-lagged)"],
        n_cheap_inputs: 22,
        cheap_sensor: true,
        target: "Kappa number (lignin content)",
        target_kind: T::Quality,
        target_measurement: "lab titration",
        has_fault_labels: false,
        input_target_lag: "EXPLICIT: column suffixes encode hours of lag applied to align inputs with the assay",
        sampling: "301 observations x 23 variables",
        deterministic_inference: "the documented hour-lags are deterministic transport delays; lagged-residual grammar, the textbook inferential-sensor case",
        access: A::OpenDownload,
        redistributed: false,
        implementation_status: Catalogued,
        // Shipped inside the GPL-licensed CRAN VIM package — reuse inherits copyleft obligations.
        license_confidence: LC::ExplicitCopyleft,
        access_confidence: AC::OpenConfirmed,
        redistribution_policy: RP::UpstreamCopyleftShareAlike,
        source_authority: SA::PackageDistribution,
        source: SourceRef { citation_key: "walkush1994kappa", authors: "Walkush & Gustafson (via R VIM package)", year: 1994, venue_or_source: "CRAN VIM dataset", url: "https://rdrr.io/cran/VIM/man/pulplignin.html", license: "GPL (VIM package)" },
    },
    SoftSensorDatasetRecordV1 {
        dataset_id: "pronto",
        name: "PRONTO multiphase flow facility",
        domain: D::MultiphaseFlow,
        cheap_sensors: &["flows", "pressures", "temperatures", "densities (+ high-frequency ultrasonic/pressure)"],
        n_cheap_inputs: 17,
        cheap_sensor: true,
        target: "flow regime / operating condition + induced faults",
        target_kind: T::FaultLabel,
        target_measurement: "logged regime/fault conditions",
        has_fault_labels: true,
        input_target_lag: "multi-rate (1 Hz process + kHz ultrasonic)",
        sampling: "Cranfield rig; segmented normal/faulty",
        deterministic_inference: "deterministic flow/in-out balance + grammar on process residuals (the project verified the rig's diverted-flow recirculates within the metered boundary)",
        access: A::OpenDownload,
        redistributed: false,
        implementation_status: Catalogued,
        // Zenodo record with a DOI; CC-BY but the exact variant should be confirmed.
        license_confidence: LC::StatedNeedsVerification,
        access_confidence: AC::OpenConfirmed,
        redistribution_policy: RP::UpstreamVerifyBeforeRedistribution,
        source_authority: SA::DoiArchive,
        source: SourceRef { citation_key: "stief2019pronto", authors: "Stief, Tan, Cao, Ottewill, Thornhill, Baranowski", year: 2019, venue_or_source: "Zenodo (J. Process Control 79)", url: "https://zenodo.org/records/1341583", license: "CC-BY (verify variant)" },
    },
    SoftSensorDatasetRecordV1 {
        dataset_id: "secom",
        name: "SECOM semiconductor",
        domain: D::Semiconductor,
        cheap_sensors: &["590 process sensor/measurement signals"],
        n_cheap_inputs: 590,
        cheap_sensor: true,
        target: "pass/fail yield",
        target_kind: T::Quality,
        target_measurement: "end-of-line test (slow, expensive)",
        has_fault_labels: true,
        input_target_lag: "per-lot; ~4.5% missing values",
        sampling: "1,567 records (104 fails)",
        deterministic_inference: "deterministic feature-residual grammar for early yield-excursion flags (already in the edge 20-dataset corpus)",
        access: A::OpenDownload,
        redistributed: false,
        implementation_status: Catalogued,
        // CC BY 4.0 on the UCI ML Repository (stable dataset ID).
        license_confidence: LC::ExplicitOpen,
        access_confidence: AC::OpenConfirmed,
        redistribution_policy: RP::UpstreamPermitsAttribution,
        source_authority: SA::CuratedMlRepository,
        source: SourceRef { citation_key: "mccann2008secom", authors: "McCann, Johnston", year: 2008, venue_or_source: "UCI ML Repository #179", url: "https://archive.ics.uci.edu/dataset/179/secom", license: "CC BY 4.0" },
    },
    SoftSensorDatasetRecordV1 {
        dataset_id: "gas_sensor_drift",
        name: "Gas Sensor Array Drift",
        domain: D::GasSensing,
        cheap_sensors: &["16 metal-oxide sensors x 8 features = 128 channels"],
        n_cheap_inputs: 128,
        cheap_sensor: true,
        target: "gas type + concentration (with sensor drift over 36 months)",
        target_kind: T::Concentration,
        target_measurement: "controlled gas-delivery reference",
        has_fault_labels: false,
        input_target_lag: "drift over months is the core challenge",
        sampling: "13,910 measurements, 36 months",
        deterministic_inference: "regime-conditioned deterministic envelopes per batch (the project's flagship regime-conditioning targets exactly this drift)",
        access: A::OpenDownload,
        redistributed: false,
        implementation_status: Catalogued,
        // CC BY 4.0 on the UCI ML Repository (stable dataset ID).
        license_confidence: LC::ExplicitOpen,
        access_confidence: AC::OpenConfirmed,
        redistribution_policy: RP::UpstreamPermitsAttribution,
        source_authority: SA::CuratedMlRepository,
        source: SourceRef { citation_key: "vergara2012gas", authors: "Vergara et al.", year: 2012, venue_or_source: "UCI ML Repository #224", url: "https://archive.ics.uci.edu/dataset/224/gas+sensor+array+drift+dataset+at+different+concentrations", license: "CC BY 4.0" },
    },
    SoftSensorDatasetRecordV1 {
        dataset_id: "indpensim",
        name: "IndPenSim industrial-scale penicillin simulation",
        domain: D::Bioprocess,
        cheap_sensors: &["temperature", "pH", "dissolved oxygen", "agitation", "aeration", "feed rates", "(+ simulated Raman)"],
        n_cheap_inputs: 10,
        cheap_sensor: true,
        target: "penicillin concentration, biomass, substrate",
        target_kind: T::Concentration,
        target_measurement: "offline HPLC / lab assay",
        has_fault_labels: false,
        input_target_lag: "batch dynamics; non-stationary growth phases",
        sampling: "100 batches, ~2.5 GB",
        deterministic_inference: "regime/phase-conditioned deterministic envelopes for the non-stationary fed-batch (a project failure case the regime-conditioning addresses); cheap process channels, Raman optional",
        access: A::OpenDownload,
        redistributed: false,
        implementation_status: Catalogued,
        // Mendeley Data with a DOI; "free academic" posture, no explicit open licence named.
        license_confidence: LC::ResearchUseCustomary,
        access_confidence: AC::OpenConfirmed,
        redistribution_policy: RP::UpstreamVerifyBeforeRedistribution,
        source_authority: SA::DoiArchive,
        source: SourceRef { citation_key: "goldrick2015development", authors: "Goldrick et al.", year: 2015, venue_or_source: "Mendeley Data (DOI 10.17632/pdnjz7zz5x.2)", url: "https://data.mendeley.com/datasets/pdnjz7zz5x", license: "free academic (Mendeley)" },
    },
    SoftSensorDatasetRecordV1 {
        dataset_id: "wine_quality",
        name: "Wine Quality",
        domain: D::Food,
        cheap_sensors: &["11 physicochemical assays (acidity, SO2, density, pH, sulphates, alcohol)"],
        n_cheap_inputs: 11,
        cheap_sensor: true,
        target: "sensory quality score",
        target_kind: T::Quality,
        target_measurement: "expert sensory panel",
        has_fault_labels: false,
        input_target_lag: "none (per-sample)",
        sampling: "~6,500 samples",
        deterministic_inference: "deterministic envelope grammar on physicochemical residuals (already in the edge corpus)",
        access: A::OpenDownload,
        redistributed: false,
        implementation_status: Catalogued,
        // CC BY 4.0 on the UCI ML Repository (stable dataset ID).
        license_confidence: LC::ExplicitOpen,
        access_confidence: AC::OpenConfirmed,
        redistribution_policy: RP::UpstreamPermitsAttribution,
        source_authority: SA::CuratedMlRepository,
        source: SourceRef { citation_key: "cortez2009wine", authors: "Cortez et al.", year: 2009, venue_or_source: "UCI ML Repository #186", url: "https://archive.ics.uci.edu/dataset/186/wine+quality", license: "CC BY 4.0" },
    },
    SoftSensorDatasetRecordV1 {
        dataset_id: "tecator_nir",
        name: "Tecator NIR meat",
        domain: D::Food,
        cheap_sensors: &["100-channel NIR absorbance (850-1050 nm)"],
        n_cheap_inputs: 100,
        cheap_sensor: false,
        target: "fat, water, protein content",
        target_kind: T::Composition,
        target_measurement: "lab reference chemistry",
        has_fault_labels: false,
        input_target_lag: "per-sample",
        sampling: "240 samples",
        deterministic_inference: "SPECTROSCOPY input (not the cheap-sensor thesis); kept for contrast / spectral-identity witness",
        access: A::OpenDownload,
        redistributed: false,
        implementation_status: Catalogued,
        // Re-hosted on OpenML (stable ID) from StatLib; "public" but exact terms unstated.
        license_confidence: LC::StatedNeedsVerification,
        access_confidence: AC::OpenConfirmed,
        redistribution_policy: RP::UpstreamVerifyBeforeRedistribution,
        source_authority: SA::CuratedMlRepository,
        source: SourceRef { citation_key: "tecator", authors: "Tecator / StatLib", year: 0, venue_or_source: "OpenML #505", url: "https://www.openml.org/d/505", license: "public (StatLib)" },
    },
    SoftSensorDatasetRecordV1 {
        dataset_id: "corn_nir",
        name: "Corn NIR (Eigenvector)",
        domain: D::Food,
        cheap_sensors: &["700-channel NIR on 3 instruments"],
        n_cheap_inputs: 700,
        cheap_sensor: false,
        target: "moisture, oil, protein, starch",
        target_kind: T::Composition,
        target_measurement: "lab reference chemistry",
        has_fault_labels: false,
        input_target_lag: "per-sample; calibration-transfer across instruments",
        sampling: "80 samples x 3 instruments",
        deterministic_inference: "SPECTROSCOPY input (not the cheap-sensor thesis); contrast / calibration-transfer",
        access: A::OpenDownload,
        redistributed: false,
        implementation_status: Catalogued,
        // Single-vendor host (eigenvector.com); "public" but no explicit licence or stable ID.
        license_confidence: LC::StatedNeedsVerification,
        access_confidence: AC::OpenMirrorUnverified,
        redistribution_policy: RP::UpstreamVerifyBeforeRedistribution,
        source_authority: SA::AuthorOrVendorHost,
        source: SourceRef { citation_key: "corn_eigenvector", authors: "Eigenvector Research", year: 0, venue_or_source: "eigenvector.com/data/Corn", url: "https://eigenvector.com/data/Corn/", license: "public" },
    },
    SoftSensorDatasetRecordV1 {
        dataset_id: "swat",
        name: "SWaT Secure Water Treatment",
        domain: D::Wastewater,
        cheap_sensors: &["tank levels (LIT)", "flows (FIT)", "pressures (PIT/DPIT)", "pH/ORP/conductivity", "pump/valve states"],
        n_cheap_inputs: 51,
        cheap_sensor: true,
        target: "normal/attack label (physically-manifesting faults)",
        target_kind: T::FaultLabel,
        target_measurement: "documented attack windows",
        has_fault_labels: true,
        input_target_lag: "1 s sampling; attack onset documented",
        sampling: "11 days, 1 s (real testbed)",
        deterministic_inference: "the project ran the deterministic T101 mass-balance witness (LIT101 vs FIT101/FIT201) on it; GATED data, provenance only",
        access: A::Gated,
        redistributed: false,
        implementation_status: Catalogued,
        // iTrust/SUTD testbed under a signed data-use agreement; redistribution prohibited.
        license_confidence: LC::AgreementGoverned,
        access_confidence: AC::AgreementRequired,
        redistribution_policy: RP::ProhibitedByAgreement,
        source_authority: SA::GovernedTestbed,
        source: SourceRef { citation_key: "goh2016swat", authors: "Goh, Adepu, Junejo, Mathur (iTrust/SUTD)", year: 2016, venue_or_source: "iTrust labs (data-use agreement)", url: "https://itrust.sutd.edu.sg/itrust-labs_datasets/", license: "iTrust DUA (gated)" },
    },
    SoftSensorDatasetRecordV1 {
        dataset_id: "wadi",
        name: "WADI Water Distribution",
        domain: D::Wastewater,
        cheap_sensors: &["flows", "pressures", "tank levels", "valve/pump status", "analyzers"],
        n_cheap_inputs: 123,
        cheap_sensor: true,
        target: "normal/attack label (leak/diversion, sensor spoofing)",
        target_kind: T::FaultLabel,
        target_measurement: "documented attack windows",
        has_fault_labels: true,
        input_target_lag: "1 s sampling",
        sampling: "16 days, 1 s (real testbed)",
        deterministic_inference: "tank volume-balance witnesses (level vs metered flows); GATED data, provenance only",
        access: A::Gated,
        redistributed: false,
        implementation_status: Catalogued,
        // iTrust/SUTD testbed under a signed data-use agreement; redistribution prohibited.
        license_confidence: LC::AgreementGoverned,
        access_confidence: AC::AgreementRequired,
        redistribution_policy: RP::ProhibitedByAgreement,
        source_authority: SA::GovernedTestbed,
        source: SourceRef { citation_key: "ahmed2017wadi", authors: "Ahmed et al. (iTrust/SUTD)", year: 2017, venue_or_source: "iTrust labs (data-use agreement)", url: "https://itrust.sutd.edu.sg/itrust-labs_datasets/", license: "iTrust DUA (gated)" },
    },
];
