//! Deterministic terminal dashboard replay for DSFB semiotics runs.
//!
//! The dashboard consumes typed replay events derived from completed engine outputs and
//! evaluation summaries. It does not recompute residual, syntax, grammar, semantics, or
//! comparator logic in the UI layer.

use anyhow::{anyhow, Result};
use ratatui::buffer::Buffer;
use ratatui::layout::{Constraint, Direction, Layout, Rect};
use ratatui::widgets::{Block, Borders, Paragraph, Widget, Wrap};
use serde::{Deserialize, Serialize};

use crate::engine::types::{EngineOutputBundle, GrammarState, ScenarioOutput};
use crate::evaluation::types::{BaselineComparatorResult, ScenarioEvaluationSummary};

/// Stable schema identifier for typed dashboard replay events.
pub const DASHBOARD_EVENT_SCHEMA_VERSION: &str = "dsfb-semiotics-dashboard-event-stream/v1";

/// Deterministic dashboard replay settings.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct DashboardReplayConfig {
    pub width: u16,
    pub height: u16,
    pub max_frames: Option<usize>,
    pub scenario_filter: Option<String>,
}

impl Default for DashboardReplayConfig {
    fn default() -> Self {
        Self {
            width: 120,
            height: 38,
            max_frames: None,
            scenario_filter: None,
        }
    }
}

/// One replayable dashboard event derived from the layered engine outputs.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct DashboardReplayEvent {
    pub schema_version: String,
    pub engine_version: String,
    pub bank_version: String,
    pub scenario_id: String,
    pub scenario_title: String,
    pub frame_index: usize,
    pub total_frames: usize,
    pub step: usize,
    pub time: f64,
    pub residual_norm: f64,
    pub drift_norm: f64,
    pub slew_norm: f64,
    pub projection_1: f64,
    pub projection_2: f64,
    pub projection_3: f64,
    pub syntax_label: String,
    pub grammar_state: String,
    pub grammar_margin: f64,
    pub semantic_disposition: String,
    pub semantic_candidates: String,
    pub selected_heuristics: String,
    pub admissibility_audit: String,
    pub comparator_alarms: String,
    pub event_log: String,
}

/// One scenario-specific replay stream consumed by the ratatui dashboard.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct DashboardReplayStream {
    pub schema_version: String,
    pub engine_version: String,
    pub bank_version: String,
    pub input_mode: String,
    pub scenario_id: String,
    pub scenario_title: String,
    pub events: Vec<DashboardReplayEvent>,
}

/// Deterministic replay bundle rendered by the terminal dashboard.
#[derive(Clone, Debug)]
pub struct DashboardReplay {
    config: DashboardReplayConfig,
    streams: Vec<DashboardReplayStream>,
}

impl DashboardReplay {
    /// Builds a deterministic dashboard replay from already-computed engine outputs.
    pub fn from_bundle(bundle: &EngineOutputBundle, config: DashboardReplayConfig) -> Result<Self> {
        let streams = bundle
            .scenario_outputs
            .iter()
            .filter(|scenario| {
                config
                    .scenario_filter
                    .as_ref()
                    .map(|filter| &scenario.record.id == filter)
                    .unwrap_or(true)
            })
            .map(|scenario| build_stream(bundle, scenario))
            .collect::<Result<Vec<_>>>()?;

        if streams.is_empty() {
            return Err(anyhow!(
                "dashboard replay did not find any scenario outputs matching the selected filter"
            ));
        }

        Ok(Self { config, streams })
    }

    /// Returns the typed replay streams rendered by the dashboard.
    #[must_use]
    pub fn streams(&self) -> &[DashboardReplayStream] {
        &self.streams
    }

    /// Renders all configured replay streams as deterministic plain text generated by ratatui.
    pub fn render_replay_ascii(&self) -> Result<String> {
        let mut sections = Vec::new();
        for stream in &self.streams {
            let frame_limit = self
                .config
                .max_frames
                .unwrap_or(stream.events.len())
                .min(stream.events.len());
            for event in stream.events.iter().take(frame_limit) {
                sections.push(render_frame_ascii(
                    stream,
                    event,
                    self.config.width.max(80),
                    self.config.height.max(24),
                ));
            }
        }
        Ok(sections.join("\n\n"))
    }

    /// Prints the replay to stdout.
    pub fn print_replay(&self) -> Result<()> {
        println!("{}", self.render_replay_ascii()?);
        Ok(())
    }
}

fn build_stream(
    bundle: &EngineOutputBundle,
    scenario: &ScenarioOutput,
) -> Result<DashboardReplayStream> {
    let evaluation = bundle
        .evaluation
        .scenario_evaluations
        .iter()
        .find(|item| item.scenario_id == scenario.record.id)
        .ok_or_else(|| anyhow!("missing scenario evaluation for `{}`", scenario.record.id))?;
    let baselines = bundle
        .evaluation
        .baseline_results
        .iter()
        .filter(|item| item.scenario_id == scenario.record.id)
        .cloned()
        .collect::<Vec<_>>();

    Ok(DashboardReplayStream {
        schema_version: DASHBOARD_EVENT_SCHEMA_VERSION.to_string(),
        engine_version: bundle.run_metadata.crate_version.clone(),
        bank_version: bundle.run_metadata.bank.bank_version.clone(),
        input_mode: bundle.run_metadata.input_mode.clone(),
        scenario_id: scenario.record.id.clone(),
        scenario_title: scenario.record.title.clone(),
        events: build_events(bundle, scenario, evaluation, &baselines),
    })
}

fn build_events(
    bundle: &EngineOutputBundle,
    scenario: &ScenarioOutput,
    evaluation: &ScenarioEvaluationSummary,
    baselines: &[BaselineComparatorResult],
) -> Vec<DashboardReplayEvent> {
    let mut log = Vec::new();
    let total_frames = scenario.sign.samples.len();
    let mut previous_state = None;

    scenario
        .sign
        .samples
        .iter()
        .zip(&scenario.grammar)
        .map(|(sample, grammar)| {
            if sample.step == 0 {
                log.push(format!(
                    "start scenario={} t={:.3}",
                    scenario.record.id, sample.time
                ));
            }

            if previous_state != Some(grammar.state) {
                log.push(format!(
                    "grammar -> {} at step {}",
                    grammar_state_label(grammar.state),
                    sample.step
                ));
                previous_state = Some(grammar.state);
            }

            for comparator in baselines {
                if comparator.triggered && comparator.first_trigger_step == Some(sample.step) {
                    log.push(format!(
                        "{} alarm at t={:.3}",
                        comparator.comparator_label,
                        comparator.first_trigger_time.unwrap_or(sample.time)
                    ));
                }
            }

            let active_alarms = baselines
                .iter()
                .filter(|result| {
                    result.triggered
                        && result
                            .first_trigger_step
                            .map(|step| step <= sample.step)
                            .unwrap_or(false)
                })
                .map(|result| result.comparator_label.clone())
                .collect::<Vec<_>>();
            let recent_log = log.iter().rev().take(4).cloned().collect::<Vec<_>>();
            let mut recent_log = recent_log.into_iter().rev().collect::<Vec<_>>();
            if recent_log.is_empty() {
                recent_log.push("no transitions yet".to_string());
            }

            DashboardReplayEvent {
                schema_version: DASHBOARD_EVENT_SCHEMA_VERSION.to_string(),
                engine_version: bundle.run_metadata.crate_version.clone(),
                bank_version: bundle.run_metadata.bank.bank_version.clone(),
                scenario_id: scenario.record.id.clone(),
                scenario_title: scenario.record.title.clone(),
                frame_index: sample.step,
                total_frames,
                step: sample.step,
                time: sample.time,
                residual_norm: sample.residual_norm,
                drift_norm: sample.drift_norm,
                slew_norm: sample.slew_norm,
                projection_1: sample.projection[0],
                projection_2: sample.projection[1],
                projection_3: sample.projection[2],
                syntax_label: scenario.syntax.trajectory_label.clone(),
                grammar_state: grammar_state_label(grammar.state).to_string(),
                grammar_margin: grammar.margin,
                semantic_disposition: format!("{:?}", scenario.semantics.disposition),
                semantic_candidates: joined_candidates(scenario),
                selected_heuristics: joined_selected_heuristics(scenario),
                admissibility_audit: format!(
                    "post_admissibility={} post_scope={} rejected_scope={}",
                    evaluation.heuristic_candidates_post_admissibility,
                    evaluation.heuristic_candidates_post_scope,
                    evaluation.heuristics_rejected_by_scope
                ),
                comparator_alarms: if active_alarms.is_empty() {
                    "none".to_string()
                } else {
                    active_alarms.join(" | ")
                },
                event_log: recent_log.join(" | "),
            }
        })
        .collect()
}

fn joined_candidates(scenario: &ScenarioOutput) -> String {
    let joined = scenario
        .semantics
        .candidates
        .iter()
        .map(|candidate| candidate.entry.short_label.clone())
        .collect::<Vec<_>>()
        .join(" | ");
    if joined.is_empty() {
        "none".to_string()
    } else {
        joined
    }
}

fn joined_selected_heuristics(scenario: &ScenarioOutput) -> String {
    if scenario.semantics.selected_heuristic_ids.is_empty() {
        "none".to_string()
    } else {
        scenario.semantics.selected_heuristic_ids.join(" | ")
    }
}

fn grammar_state_label(state: GrammarState) -> &'static str {
    match state {
        GrammarState::Admissible => "admissible",
        GrammarState::Boundary => "boundary",
        GrammarState::Violation => "violation",
    }
}

fn render_frame_ascii(
    stream: &DashboardReplayStream,
    event: &DashboardReplayEvent,
    width: u16,
    height: u16,
) -> String {
    let area = Rect::new(0, 0, width, height);
    let mut buffer = Buffer::empty(area);

    let vertical = Layout::default()
        .direction(Direction::Vertical)
        .constraints([
            Constraint::Length(4),
            Constraint::Length(7),
            Constraint::Length(8),
            Constraint::Min(5),
        ])
        .split(area);

    let header = Layout::default()
        .direction(Direction::Horizontal)
        .constraints([
            Constraint::Percentage(34),
            Constraint::Percentage(33),
            Constraint::Percentage(33),
        ])
        .split(vertical[0]);
    let metrics = Layout::default()
        .direction(Direction::Horizontal)
        .constraints([
            Constraint::Percentage(25),
            Constraint::Percentage(25),
            Constraint::Percentage(25),
            Constraint::Percentage(25),
        ])
        .split(vertical[1]);
    let middle = Layout::default()
        .direction(Direction::Horizontal)
        .constraints([
            Constraint::Percentage(34),
            Constraint::Percentage(33),
            Constraint::Percentage(33),
        ])
        .split(vertical[2]);

    Paragraph::new(format!(
        "scenario={} frame={}/{}",
        stream.scenario_id,
        event.frame_index + 1,
        event.total_frames
    ))
    .block(
        Block::default()
            .title("Scenario / Stream")
            .borders(Borders::ALL),
    )
    .wrap(Wrap { trim: true })
    .render(header[0], &mut buffer);

    Paragraph::new(format!(
        "syntax={}\ngrammar={}\nsemantics={}",
        event.syntax_label, event.grammar_state, event.semantic_disposition
    ))
    .block(
        Block::default()
            .title("Headline State")
            .borders(Borders::ALL),
    )
    .wrap(Wrap { trim: true })
    .render(header[1], &mut buffer);

    Paragraph::new(format!(
        "candidates={}\nselected={}",
        event.semantic_candidates, event.selected_heuristics
    ))
    .block(
        Block::default()
            .title("Semantic Candidates")
            .borders(Borders::ALL),
    )
    .wrap(Wrap { trim: true })
    .render(header[2], &mut buffer);

    Paragraph::new(format!(
        "t={:.3}\nstep={}\nresidual={:.6}",
        event.time, event.step, event.residual_norm
    ))
    .block(
        Block::default()
            .title("Residual Norm")
            .borders(Borders::ALL),
    )
    .wrap(Wrap { trim: true })
    .render(metrics[0], &mut buffer);

    Paragraph::new(format!(
        "drift={:.6}\nslew={:.6}\nmargin={:.6}",
        event.drift_norm, event.slew_norm, event.grammar_margin
    ))
    .block(Block::default().title("Drift / Slew").borders(Borders::ALL))
    .wrap(Wrap { trim: true })
    .render(metrics[1], &mut buffer);

    Paragraph::new(format!(
        "p1={:.4}\np2={:.4}\np3={:.4}",
        event.projection_1, event.projection_2, event.projection_3
    ))
    .block(
        Block::default()
            .title("Projected Sign")
            .borders(Borders::ALL),
    )
    .wrap(Wrap { trim: true })
    .render(metrics[2], &mut buffer);

    Paragraph::new(format!(
        "alarms={}\naudit={}",
        event.comparator_alarms, event.admissibility_audit
    ))
    .block(
        Block::default()
            .title("Comparators / Admissibility")
            .borders(Borders::ALL),
    )
    .wrap(Wrap { trim: true })
    .render(metrics[3], &mut buffer);

    Paragraph::new(format!(
        "input_mode={}\nengine_version={}\nbank_version={}",
        stream.input_mode, stream.engine_version, stream.bank_version
    ))
    .block(Block::default().title("Run Metadata").borders(Borders::ALL))
    .wrap(Wrap { trim: true })
    .render(middle[0], &mut buffer);

    Paragraph::new(format!(
        "scenario_title={}\ntrace_step={}\nlog={}",
        event.scenario_title, event.step, event.event_log
    ))
    .block(
        Block::default()
            .title("Event / Transition Log")
            .borders(Borders::ALL),
    )
    .wrap(Wrap { trim: true })
    .render(middle[1], &mut buffer);

    let sign_timeline = build_sign_timeline(stream, event);
    Paragraph::new(sign_timeline)
        .block(
            Block::default()
                .title("Sign Timeline")
                .borders(Borders::ALL),
        )
        .wrap(Wrap { trim: true })
        .render(middle[2], &mut buffer);

    Paragraph::new(format!(
        "dashboard_schema={}\nThis ratatui replay consumes engine/evaluation events only; it does not recompute residual, syntax, grammar, semantics, or comparator logic in the UI layer.",
        DASHBOARD_EVENT_SCHEMA_VERSION
    ))
    .block(Block::default().title("Replay Note").borders(Borders::ALL))
    .wrap(Wrap { trim: true })
    .render(vertical[3], &mut buffer);

    buffer_to_string(&buffer)
}

fn build_sign_timeline(stream: &DashboardReplayStream, event: &DashboardReplayEvent) -> String {
    let upto = event.frame_index.min(stream.events.len().saturating_sub(1));
    stream.events[..=upto]
        .iter()
        .map(|item| {
            format!(
                "{:.2}/{:.2}/{:.2}",
                item.projection_1, item.projection_2, item.projection_3
            )
        })
        .collect::<Vec<_>>()
        .join(" | ")
}

fn buffer_to_string(buffer: &Buffer) -> String {
    let area = buffer.area;
    let mut lines = Vec::with_capacity(area.height as usize);
    for y in 0..area.height {
        let mut line = String::new();
        for x in 0..area.width {
            line.push_str(buffer[(x, y)].symbol());
        }
        lines.push(line.trim_end().to_string());
    }
    lines.join("\n")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::engine::config::CommonRunConfig;
    use crate::engine::pipeline::{EngineConfig, StructuralSemioticsEngine};

    #[test]
    fn dashboard_buffer_render_contains_expected_sections() {
        let engine = StructuralSemioticsEngine::new(EngineConfig::synthetic_single(
            CommonRunConfig::default(),
            "nominal_stable",
        ));
        let bundle = engine.run_selected().unwrap();
        let replay =
            DashboardReplay::from_bundle(&bundle, DashboardReplayConfig::default()).unwrap();
        let rendered = replay.render_replay_ascii().unwrap();

        assert!(rendered.contains("Scenario / Stream"));
        assert!(rendered.contains("Sign Timeline"));
        assert!(rendered.contains("Comparators / Admissibility"));
    }
}
