//! Typed replay configuration and event-stream containers shared by bundle replay and CSV replay.

use anyhow::{anyhow, Result};
use serde::{Deserialize, Serialize};

use crate::engine::types::EngineOutputBundle;

use super::build::build_streams_from_bundle;
use super::render::{render_frame_ascii, ReplayFrameChrome};

/// Stable schema identifier for typed dashboard replay events.
pub const DASHBOARD_EVENT_SCHEMA_VERSION: &str = "dsfb-semiotics-dashboard-event-stream/v1";

/// Deterministic dashboard replay settings.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct DashboardReplayConfig {
    pub width: u16,
    pub height: u16,
    pub max_frames: Option<usize>,
    pub scenario_filter: Option<String>,
    pub playback_speed: f64,
    pub start_paused: bool,
    pub source_label: Option<String>,
    pub trust_threshold: f64,
}

impl Default for DashboardReplayConfig {
    fn default() -> Self {
        Self {
            width: 120,
            height: 38,
            max_frames: None,
            scenario_filter: None,
            playback_speed: 1.0,
            start_paused: false,
            source_label: None,
            trust_threshold: 0.75,
        }
    }
}

impl DashboardReplayConfig {
    /// Validates render-facing replay settings.
    pub fn validate(&self) -> Result<()> {
        if self.width < 80 || self.height < 24 {
            return Err(anyhow!(
                "dashboard replay requires width >= 80 and height >= 24"
            ));
        }
        if !self.playback_speed.is_finite() || self.playback_speed <= 0.0 {
            return Err(anyhow!(
                "dashboard playback speed must be positive and finite; got {}",
                self.playback_speed
            ));
        }
        if !self.trust_threshold.is_finite() || !(0.0..=1.0).contains(&self.trust_threshold) {
            return Err(anyhow!(
                "dashboard trust threshold must lie in [0,1]; got {}",
                self.trust_threshold
            ));
        }
        Ok(())
    }
}

/// One replayable dashboard event derived from the layered engine outputs.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct DashboardReplayEvent {
    pub schema_version: String,
    pub engine_version: String,
    pub bank_version: String,
    pub scenario_id: String,
    pub scenario_title: String,
    pub frame_index: usize,
    pub total_frames: usize,
    pub step: usize,
    pub time: f64,
    pub residual_norm: f64,
    pub drift_norm: f64,
    pub slew_norm: f64,
    pub projection_1: f64,
    pub projection_2: f64,
    pub projection_3: f64,
    pub syntax_label: String,
    pub grammar_state: String,
    pub grammar_margin: f64,
    pub grammar_reason_text: String,
    pub trust_scalar: f64,
    pub semantic_disposition: String,
    pub semantic_candidates: String,
    pub selected_heuristics: String,
    pub admissibility_audit: String,
    pub comparator_alarms: String,
    pub event_markers: Vec<String>,
    pub event_log: String,
}

/// One scenario-specific replay stream consumed by the `ratatui` dashboard.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct DashboardReplayStream {
    pub schema_version: String,
    pub engine_version: String,
    pub bank_version: String,
    pub input_mode: String,
    pub scenario_id: String,
    pub scenario_title: String,
    pub source_label: String,
    pub events: Vec<DashboardReplayEvent>,
}

/// Deterministic replay bundle rendered by the terminal dashboard.
#[derive(Clone, Debug)]
pub struct DashboardReplay {
    config: DashboardReplayConfig,
    streams: Vec<DashboardReplayStream>,
}

impl DashboardReplay {
    /// Builds a deterministic dashboard replay from already-computed engine outputs.
    pub fn from_bundle(bundle: &EngineOutputBundle, config: DashboardReplayConfig) -> Result<Self> {
        config.validate()?;
        let streams = build_streams_from_bundle(bundle, &config)?;
        if streams.is_empty() {
            return Err(anyhow!(
                "dashboard replay did not find any scenario outputs matching the selected filter"
            ));
        }
        Ok(Self { config, streams })
    }

    /// Returns the typed replay streams rendered by the dashboard.
    #[must_use]
    pub fn streams(&self) -> &[DashboardReplayStream] {
        &self.streams
    }

    /// Renders all configured replay streams as deterministic plain text generated by `ratatui`.
    pub fn render_replay_ascii(&self) -> Result<String> {
        let mut sections = Vec::new();
        for stream in &self.streams {
            let frame_limit = self
                .config
                .max_frames
                .unwrap_or(stream.events.len())
                .min(stream.events.len());
            for event in stream.events.iter().take(frame_limit) {
                sections.push(render_frame_ascii(
                    stream,
                    event,
                    self.config.width.max(80),
                    self.config.height.max(24),
                    &ReplayFrameChrome {
                        replay_mode_label: if stream.input_mode == "csv" {
                            "REPLAY MODE: CSV"
                        } else {
                            "REPLAY MODE: BUNDLE"
                        },
                        source_label: &stream.source_label,
                        status_label: if self.config.start_paused {
                            "paused"
                        } else {
                            "running"
                        },
                        playback_speed: self.config.playback_speed,
                        current_time: event.time,
                    },
                ));
            }
        }
        Ok(sections.join("\n\n"))
    }

    /// Prints the replay to stdout.
    pub fn print_replay(&self) -> Result<()> {
        println!("{}", self.render_replay_ascii()?);
        Ok(())
    }
}
