//! Emit the augmenting `dsfb.bib` consumed by the master `.tex`.
//!
//! Synthesises placeholder `@unpublished` and `@misc` entries for every
//! `paperstack_cite` and `public_dataset` declared in the YAML Parts,
//! deduplicated alphabetically.

use crate::schema::Part;
use std::collections::BTreeSet;
use std::fmt::Write;

/// Emit a small dsfb.bib that augments the hand-curated dsfb_canon.bib.
/// We synthesise placeholder entries for every paperstack_cite and public_dataset
/// declared in the YAML, deduplicated.
pub fn emit_bib(parts: &[Part]) -> anyhow::Result<String> {
    let mut paperstack: BTreeSet<String> = BTreeSet::new();
    let mut datasets: BTreeSet<String> = BTreeSet::new();
    for p in parts {
        for c in &p.chapters {
            if let Some(s) = &c.paperstack_cite {
                paperstack.insert(s.clone());
            }
            if let Some(s) = &c.public_dataset {
                datasets.insert(s.clone());
            }
        }
    }

    let mut out = String::new();
    writeln!(
        out,
        "% generated/dsfb.bib --- auto-generated by dsfb-atlas. Do not edit by hand.\n"
    )?;
    writeln!(out, "% --- Paperstack entries ---")?;
    for (i, p) in paperstack.iter().enumerate() {
        let key = format!("paperstack-{:03}", i + 1);
        writeln!(
            out,
            "@unpublished{{{key},\n  author = {{Riaan {{de Beer}}}},\n  title = {{{title}}},\n  note = {{Internal paperstack disclosure; see Appendix A.4 chain of priority.}},\n  year = {{2026}}\n}}\n",
            key = key,
            title = p.replace('{', "(").replace('}', ")")
        )?;
    }
    writeln!(out, "% --- Public datasets ---")?;
    for (i, d) in datasets.iter().enumerate() {
        let key = format!("dataset-{:03}", i + 1);
        writeln!(
            out,
            "@misc{{{key},\n  title = {{{title}}},\n  note = {{Public dataset cited by atlas T3 entries.}},\n  year = {{2026}}\n}}\n",
            key = key,
            title = d.replace('{', "(").replace('}', ")")
        )?;
    }

    Ok(out)
}
