//! Emit the longtable theorem index consumed by Appendix G.
//!
//! Produces one `\begin{longtable}` block listing every atlas theorem
//! with its method name, chapter name, and empirical-anchor tier.

use crate::schema::Part;
use std::fmt::Write;

/// Emit a longtable theorem index spanning all 10,000 atlas theorems.
pub fn emit_index(parts: &[Part]) -> anyhow::Result<String> {
    let mut out = String::new();
    writeln!(out, "% generated/index_longtable.tex --- auto-generated by dsfb-atlas.")?;
    writeln!(out, "% Spans 10,000 atlas theorems. Use \\input from app_g_theorem_index.tex.")?;
    writeln!(out)?;
    writeln!(
        out,
        "{{\\scriptsize\n\\setlength{{\\tabcolsep}}{{4pt}}\n\\begin{{longtable}}{{@{{}}p{{2.5cm}}p{{4.5cm}}p{{4.5cm}}c@{{}}}}\n\\toprule"
    )?;
    writeln!(out, "Theorem ID & Method & Chapter & Tier \\\\\n\\midrule")?;
    writeln!(out, "\\endhead")?;

    for part in parts {
        for chapter in &part.chapters {
            let tier = chapter
                .anchor_tier
                .clone()
                .unwrap_or_else(|| part.default_anchor_tier.clone());
            for (s_idx, stem) in chapter.stems.iter().enumerate() {
                for (m_idx, modifier) in chapter.modifiers.iter().enumerate() {
                    let theorem_index = s_idx * chapter.modifiers.len() + m_idx + 1;
                    let theorem_id = format!("{}-T{:04}", chapter.chapter_id, theorem_index);
                    let method = format!("{} {}", modifier, stem);
                    writeln!(
                        out,
                        "\\texttt{{{}}} & {} & {} & {} \\\\",
                        theorem_id,
                        latex_escape_short(&method),
                        latex_escape_short(&chapter.chapter_name),
                        tier
                    )?;
                }
            }
        }
    }
    writeln!(out, "\\bottomrule")?;
    writeln!(out, "\\end{{longtable}}\n}}")?;
    Ok(out)
}

fn latex_escape_short(s: &str) -> String {
    s.replace('&', "\\&")
        .replace('%', "\\%")
        .replace('#', "\\#")
        .replace('_', "\\_")
}
