#!/usr/bin/env python3
"""Generate the WASM court-simulator's bundled sample residual stream.

This is a SYNTHETIC chemical-process residual — a CSTR / stirred-reactor SPE-style monitoring residual
(squared-prediction-error magnitude in approximately sigma units) — clearly labelled, **NOT plant data**
(this project never redistributes real/gated plant data). It is shaped to exercise the full DSFB grammar
under the default admissibility envelope (k=3) so the in-browser what-if is legible:

    nominal noise  ->  drift ramp (DriftAccum)  ->  a slew spike (SlewSpike / Compound)
                   ->  a sustained envelope breach (EnvViolation)  ->  decay through Recovery to Nominal.

Deterministic (SplitMix64, mirroring datasets.rs::Rng and gen_instrumented.py), no third-party deps.
Run:  python3 gen_sample_residuals.py   ->  writes sample_residuals.json next to this script.
"""
import json
import math
import os

HERE = os.path.dirname(os.path.abspath(__file__))


class Rng:
    """SplitMix64 -> uniform/normal, identical scheme to the Rust/edge generators."""

    def __init__(self, seed):
        self.s = seed & 0xFFFFFFFFFFFFFFFF

    def _next(self):
        self.s = (self.s + 0x9E3779B97F4A7C15) & 0xFFFFFFFFFFFFFFFF
        z = self.s
        z = ((z ^ (z >> 30)) * 0xBF58476D1CE4E5B9) & 0xFFFFFFFFFFFFFFFF
        z = ((z ^ (z >> 27)) * 0x94D049BB133111EB) & 0xFFFFFFFFFFFFFFFF
        return (z ^ (z >> 31)) & 0xFFFFFFFFFFFFFFFF

    def uniform(self):
        return (self._next() >> 11) / float(1 << 53)

    def normal(self, sd):
        u1 = max(self.uniform(), 1e-12)
        u2 = self.uniform()
        z = math.sqrt(-2.0 * math.log(u1)) * math.cos(2.0 * math.pi * u2)
        return max(-5.0, min(5.0, z)) * sd


def gen(n=480, onset_drift=300, spike=340, breach_end=420):
    """Build the residual stream. The phases are chosen relative to the default envelope (k=3, drift band
    0.6k=1.8, slew band 2k=6, window 16) so each grammar state actually appears."""
    rng = Rng(20260526)
    r = []
    for k in range(n):
        if k < onset_drift:
            v = rng.normal(0.45)  # nominal: small zero-mean residual noise, |r| stays well inside ±3
        elif k < spike:
            # Drift ramp: the windowed mean (drift delta) climbs past 0.6k=1.8 -> DriftAccum, then the
            # raw residual itself approaches the boundary -> BoundaryGrazing near the end of the ramp.
            v = 0.06 * (k - onset_drift) + rng.normal(0.35)
        elif k == spike:
            v = 9.0  # a single large jump: first-difference (slew) breaches ±6 -> SlewSpike / Compound
        elif k < breach_end:
            v = 4.2 + rng.normal(0.30)  # sustained level beyond k=3 -> EnvViolation
        else:
            # Exponential decay back toward nominal: crosses the boundary, lingers as drift, then recovers.
            v = 4.2 * math.exp(-(k - breach_end) / 12.0) + rng.normal(0.30)
        r.append(round(v, 4))
    return r


def main():
    residuals = gen()
    doc = {
        "schema": "dsfb_wasm_sample_v1",
        "label": "synthetic CSTR/reactor SPE-style residual (NOT plant data)",
        "note": (
            "Deterministic synthetic demonstrator (SplitMix64, seed 20260526). Shape: nominal -> drift "
            "ramp -> slew spike -> sustained envelope breach -> recovery. Generated by "
            "gen_sample_residuals.py. This project never redistributes real plant data."
        ),
        "k_default": 3.0,
        "band_default": 0.1,
        "window_default": 16,
        "n": len(residuals),
        "residuals": residuals,
    }
    out = os.path.join(HERE, "sample_residuals.json")
    with open(out, "w") as f:
        json.dump(doc, f, separators=(",", ":"))
    print(f"wrote {out} ({len(residuals)} samples)")


if __name__ == "__main__":
    main()
