//! Static-seed → TOML dump producer.
//!
//! Emits the corpus in the same subset format that [`crate::toml_parser`]
//! consumes. The dump is the bootstrap path for `corpus/corpus.toml`
//! and is also the foundation of the T.2 equivalence tests:
//!
//! 1. Dump the static seed to a TOML string.
//! 2. Parse the string with [`crate::toml_parser`].
//! 3. Load the AST with [`crate::loader`].
//! 4. Assert every loaded record matches its static counterpart
//!    field-by-field via
//!    [`crate::loader::LoadedLiteratureDetector::matches_static`].
//!
//! This dump → parse → load round trip is the load-bearing
//! equivalence guarantee that T.2 ships.

extern crate alloc;
use alloc::string::{String, ToString};
use core::fmt::Write;

use crate::types::{
    AxisBindingSet, DomainTagSet, GenealogyEdges, InputRequirementSet, LiteratureDetector,
    SourceRef,
};

/// Render every record in `records` as one big TOML document.
///
/// Output is deterministic: two calls with the same input produce
/// the same byte stream. Record order matches the input order.
#[must_use]
pub fn dump_to_string(records: &[LiteratureDetector]) -> String {
    let mut out = String::new();
    let _ = writeln!(
        out,
        "# DSFB-GPU-Atlas literature detector corpus -- TOML source ingestion"
    );
    let _ = writeln!(
        out,
        "# Generated by `dsfb_gpu_atlas_corpus::dump::dump_to_string` from the"
    );
    let _ = writeln!(
        out,
        "# static seed in `crates/dsfb-gpu-atlas-corpus/src/seed.rs`. The"
    );
    let _ = writeln!(
        out,
        "# static seed remains the canonical fixture at T.2; this file is the"
    );
    let _ = writeln!(
        out,
        "# parallel data-path proven equivalent by the T.2 acceptance tests."
    );
    let _ = writeln!(out, "#");
    let _ = writeln!(
        out,
        "# Schema: every `[[detector]]` block carries the fields the verifier"
    );
    let _ = writeln!(
        out,
        "# requires (see `src/types.rs` for the LiteratureDetector struct)."
    );
    let _ = writeln!(out);
    for record in records {
        dump_record(&mut out, record);
    }
    out
}

fn dump_record(out: &mut String, r: &LiteratureDetector) {
    dump_record_header(out, r);
    dump_record_parameter_bounds(out, r);
    dump_record_genealogy(out, r);
    dump_record_constitution(out, r);
    for s in r.source_refs {
        dump_source_ref(out, s);
    }
    let _ = writeln!(out);
}

fn dump_record_header(out: &mut String, r: &LiteratureDetector) {
    let _ = writeln!(out, "[[detector]]");
    let _ = writeln!(out, "canonical_id = {}", r.canonical_id.0);
    let _ = writeln!(out, "display_name = {}", quote(r.display_name));
    let _ = writeln!(out, "aliases = {}", string_array(r.aliases));
    let _ = writeln!(
        out,
        "primitive_family = {}",
        quote(r.primitive_family.as_str())
    );
    let _ = writeln!(
        out,
        "mathematical_form = {}",
        quote(r.mathematical_form.as_str())
    );
    let _ = writeln!(
        out,
        "decision_functional = {}",
        quote(r.decision_functional.as_str())
    );
    let _ = writeln!(
        out,
        "input_requirements = {}",
        input_requirement_names(r.input_requirements)
    );
    let _ = writeln!(
        out,
        "origin_domains = {}",
        domain_tag_names(r.origin_domains)
    );
    let _ = writeln!(out, "output_witness = {}", quote(r.output_witness.as_str()));
    let _ = writeln!(out, "witness_role = {}", quote(r.witness_role.as_str()));
    let _ = writeln!(
        out,
        "negative_witness_kind = {}",
        quote(r.negative_witness_kind.as_str())
    );
    let _ = writeln!(out, "fusion_axes = {}", axis_binding_names(r.fusion_axes));
    let _ = writeln!(
        out,
        "confuser_profile = {}",
        quote(r.confuser_profile.as_str())
    );
    let _ = writeln!(
        out,
        "deterministic_status = {}",
        quote(r.deterministic_status.as_str())
    );
    let _ = writeln!(
        out,
        "implementation_status = {}",
        quote(r.implementation_status.as_str())
    );
    let _ = writeln!(out, "gpu_family = {}", quote(r.gpu_family.as_str()));
    let _ = writeln!(out, "duplicate_group = {}", r.duplicate_group.0);
    let _ = writeln!(
        out,
        "lifecycle_state = {}",
        quote(r.lifecycle_state.as_str())
    );
    let _ = writeln!(out);
}

fn dump_record_parameter_bounds(out: &mut String, r: &LiteratureDetector) {
    let _ = writeln!(out, "[detector.parameter_bounds]");
    let _ = writeln!(out, "axis_count = {}", r.parameter_bounds.axis_count);
    let _ = writeln!(
        out,
        "description = {}",
        quote(r.parameter_bounds.description)
    );
    let _ = writeln!(out);
}

fn dump_record_genealogy(out: &mut String, r: &LiteratureDetector) {
    let _ = writeln!(out, "[detector.genealogy]");
    let _ = writeln!(out, "derived_from = {}", id_array(r.genealogy.derived_from));
    let _ = writeln!(out, "generalizes = {}", id_array(r.genealogy.generalizes));
    let _ = writeln!(
        out,
        "special_case_of = {}",
        id_array(r.genealogy.special_case_of)
    );
    let _ = writeln!(out, "is_origin = {}", r.genealogy.is_origin);
    let _ = writeln!(out);
}

fn dump_record_constitution(out: &mut String, r: &LiteratureDetector) {
    let _ = writeln!(out, "[detector.constitution_compliance]");
    let cf = r.constitution_compliance;
    let _ = writeln!(
        out,
        "declared_input_contract = {}",
        cf.declared_input_contract
    );
    let _ = writeln!(out, "declared_output_type = {}", cf.declared_output_type);
    let _ = writeln!(
        out,
        "declared_deterministic_form = {}",
        cf.declared_deterministic_form
    );
    let _ = writeln!(out, "declared_provenance = {}", cf.declared_provenance);
    let _ = writeln!(
        out,
        "declared_equivalence_status = {}",
        cf.declared_equivalence_status
    );
    let _ = writeln!(out, "declared_witness_role = {}", cf.declared_witness_role);
    let _ = writeln!(
        out,
        "declared_activation_conditions = {}",
        cf.declared_activation_conditions
    );
    let _ = writeln!(
        out,
        "declared_failure_confuser_modes = {}",
        cf.declared_failure_confuser_modes
    );
    let _ = writeln!(out);
}

fn dump_source_ref(out: &mut String, s: &SourceRef) {
    let _ = writeln!(out, "[[detector.source_refs]]");
    let _ = writeln!(out, "citation_key = {}", quote(s.citation_key));
    let _ = writeln!(out, "title = {}", quote(s.title));
    let _ = writeln!(out, "authors = {}", quote(s.authors));
    let _ = writeln!(out, "year = {}", s.year);
    let _ = writeln!(out, "venue_or_source = {}", quote(s.venue_or_source));
    let doi = s.doi_or_url.unwrap_or("");
    let _ = writeln!(out, "doi_or_url = {}", quote(doi));
    let _ = writeln!(out, "notes = {}", quote(s.notes));
    let _ = writeln!(out);
}

fn quote(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for ch in s.chars() {
        match ch {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\t' => out.push_str("\\t"),
            '\r' => out.push_str("\\r"),
            other => out.push(other),
        }
    }
    out.push('"');
    out
}

fn string_array(values: &[&str]) -> String {
    if values.is_empty() {
        return "[]".to_string();
    }
    let mut out = String::from("[");
    for (i, v) in values.iter().enumerate() {
        if i > 0 {
            out.push_str(", ");
        }
        out.push_str(&quote(v));
    }
    out.push(']');
    out
}

fn id_array(values: &[crate::types::DetectorCanonicalId]) -> String {
    if values.is_empty() {
        return "[]".to_string();
    }
    let mut out = String::from("[");
    for (i, v) in values.iter().enumerate() {
        if i > 0 {
            out.push_str(", ");
        }
        let _ = write!(out, "{}", v.0);
    }
    out.push(']');
    out
}

fn input_requirement_names(set: InputRequirementSet) -> String {
    let mut names: alloc::vec::Vec<&'static str> = alloc::vec::Vec::new();
    for &(bit, name) in InputRequirementSet::bit_names() {
        if set.0 & bit != 0 {
            names.push(name);
        }
    }
    string_array_str(&names)
}

fn axis_binding_names(set: AxisBindingSet) -> String {
    let mut names: alloc::vec::Vec<&'static str> = alloc::vec::Vec::new();
    for &(bit, name) in AxisBindingSet::bit_names() {
        if set.0 & bit != 0 {
            names.push(name);
        }
    }
    string_array_str(&names)
}

fn domain_tag_names(set: DomainTagSet) -> String {
    let mut names: alloc::vec::Vec<&'static str> = alloc::vec::Vec::new();
    for &(bit, name) in DomainTagSet::bit_names() {
        if set.0 & bit != 0 {
            names.push(name);
        }
    }
    string_array_str(&names)
}

fn string_array_str(values: &[&str]) -> String {
    if values.is_empty() {
        return "[]".to_string();
    }
    let mut out = String::from("[");
    for (i, v) in values.iter().enumerate() {
        if i > 0 {
            out.push_str(", ");
        }
        out.push_str(&quote(v));
    }
    out.push(']');
    out
}

// Silence dead-code warning when GenealogyEdges' edges types vary.
#[allow(dead_code)]
const _: () = {
    let _ = GenealogyEdges::origin().is_origin;
};
