#![no_main]

//! Fuzz target for the `pg_stat_statements` CSV adapter.
//!
//! The adapter at `src/adapters/postgres.rs` is the only adapter that
//! ingests data from a *real production engine* (Postgres), and the
//! CSV format is user-provided — an operator exports a snapshot from
//! `pg_stat_statements`. That makes its parser the trust-boundary
//! surface most exposed to malformed input in a real deployment.
//!
//! This target writes the fuzz-generated byte sequence to a temp file
//! and calls `load_pg_stat_statements`. The invariant is that the
//! adapter must *never panic*: every malformed row must be handled
//! either by `serde`-level rejection (Err) or by the explicit
//! "fewer than 2 rows" `anyhow::bail`. Panics, overflows, or UB are
//! reportable bugs.

use dsfb_database::adapters::postgres::load_pg_stat_statements;
use libfuzzer_sys::fuzz_target;
use std::io::Write;

fuzz_target!(|data: &[u8]| {
    let Ok(mut tmp) = tempfile::NamedTempFile::new() else {
        return;
    };
    if tmp.write_all(data).is_err() {
        return;
    }
    if tmp.flush().is_err() {
        return;
    }
    // The adapter returns a `Result`; both Ok and Err are acceptable.
    // We care only about the absence of panics.
    let _ = load_pg_stat_statements(tmp.path());
});
