//! Chemometric detector-atlas corpus: load + validate the canonicalised literature detector set.
//!
//! # What this module contains
//! The corpus is embedded at compile time from `corpus/chemometric_atlas.toml` (generated by
//! `scripts/gen_atlas_corpus.py`). It catalogues **57 detector entries** spanning:
//! - 4 top-level families (Classical MSPC, Dynamic/Temporal, Nonlinear/Distributional,
//!   Process-Structure).
//! - 11 primitive families (e.g. Hotelling, CUSUM, KS, kNN, spectral, …).
//! - **18 detectors** marked `implementation_status = "Executed"` — these are the detectors
//!   implemented in `detectors.rs` and run by the pipeline.
//! - **39 detectors** marked `"Catalogued"` — prior-art entries documented for completeness but
//!   not executed in this pipeline; their presence does not imply any claim of implementation.
//!
//! # Schema alignment
//! Each `CorpusDetector` entry mirrors the schema used by the broader DSFB atlas crates so that
//! corpus files can be validated and compared consistently across the project.
//!
//! # Integrity checks (enforced by `Corpus::validate`)
//! - (a) The declared `detector_count` header equals the number of parsed entries.
//! - (b) Every `detector_id` string is unique within the corpus.
//! - (c) No two entries share an identical canonical-definition fingerprint (SHA-256 over a
//!   normalised concatenation of family, primitive_family, mathematical_form,
//!   decision_functional, witness_role, fusion_axes).  Genuinely distinct detectors that
//!   happen to share a primitive mathematical form are distinguished by source_basis +
//!   display_name in a second-pass fingerprint check.
//!
//! # Determinism / replay
//! The corpus TOML is embedded with `include_str!` at compile time, so the corpus bytes are
//! identical for any binary built from the same source tree.  The `corpus_sha256` field in
//! `CorpusValidation` captures this byte fingerprint for inclusion in pipeline reports, enabling
//! byte-exact replay verification.

use crate::hashing::sha256_hex;
use serde::Deserialize;
use std::collections::BTreeSet;

// The entire corpus TOML is embedded into the binary at compile time.
// This means no file I/O is needed at runtime and the corpus bytes are stable across
// deployments of the same binary — a requirement for byte-exact replay of pipeline outputs.
const CORPUS_TOML: &str = include_str!("../corpus/chemometric_atlas.toml");

/// One detector entry in the corpus TOML.
///
/// Fields mirror the DSFB atlas schema.  String types are used throughout because the values
/// are free-form text from the TOML; structured enums would require a mapping layer.
#[derive(Debug, Clone, Deserialize)]
pub struct CorpusDetector {
    /// Sequential integer ID assigned by the corpus generator; used for stable cross-referencing.
    pub canonical_id: u32,
    /// Short snake_case identifier; must be unique within the corpus (enforced by `validate`).
    /// For executed detectors this must match `Detector::id()` in `detectors.rs`.
    pub detector_id: String,
    /// Human-readable name for reports and documentation.
    pub display_name: String,
    /// Top-level family label (one of the four project-plan families A–D).
    pub family: String,
    /// Finer-grained statistical primitive (e.g. "Hotelling", "CUSUM", "KS", "Entropy").
    pub primitive_family: String,
    /// Brief description of the mathematical estimator or test statistic.
    pub mathematical_form: String,
    /// How the statistic is compared to a limit to produce a breach decision.
    pub decision_functional: String,
    /// Role this detector plays as a witness in the DSFB evidence framework.
    pub witness_role: String,
    /// DSFB fusion axes this detector contributes evidence to.
    pub fusion_axes: Vec<String>,
    /// Application domains from which this detector originates (e.g. "MSPC", "SPC", "FDI").
    pub origin_domains: Vec<String>,
    /// Whether the detector produces deterministic output ("Deterministic" / "Stochastic").
    pub deterministic_status: String,
    /// "Executed" if implemented in `detectors.rs` and run by the pipeline;
    /// "Catalogued" if present as prior-art documentation only.
    pub implementation_status: String,
    /// Literature reference or methodology basis for the detector.
    pub source_basis: String,
}

/// The top-level corpus document parsed from `chemometric_atlas.toml`.
///
/// `detector_count` is a declared header field in the TOML; `validate` checks it matches
/// `detectors.len()`.  The `#[serde(rename = "detector")]` attribute reflects the TOML
/// convention of using `[[detector]]` array-of-tables rather than `[[detectors]]`.
#[derive(Debug, Clone, Deserialize)]
pub struct Corpus {
    /// Schema version of the corpus TOML format; used for forward-compatibility checks.
    pub schema_version: u32,
    pub corpus_name: String,
    /// Declared total number of detector entries; validated against `detectors.len()`.
    pub detector_count: usize,
    #[serde(rename = "detector")]
    pub detectors: Vec<CorpusDetector>,
}

/// Summary statistics produced by `Corpus::validate`, suitable for inclusion in pipeline reports.
///
/// All counts are derived by iterating `Corpus::detectors`; no external lookups are performed.
/// `corpus_sha256` is the SHA-256 of the raw TOML bytes (i.e. of `CORPUS_TOML`), providing a
/// stable fingerprint for replay verification.
#[derive(Debug)]
pub struct CorpusValidation {
    /// Total number of detector entries in the corpus.
    pub n_total: usize,
    /// Number of entries with `implementation_status == "Executed"` (implemented in `detectors.rs`).
    pub n_executed: usize,
    /// Number of entries with `implementation_status != "Executed"` (catalogued prior art only).
    pub n_catalogued: usize,
    /// Number of distinct `primitive_family` values observed across all entries.
    pub n_primitive_families: usize,
    /// SHA-256 hex digest of the embedded corpus TOML bytes.
    pub corpus_sha256: String,
}

impl Corpus {
    /// Parse the compile-time embedded corpus TOML and return a `Corpus`.
    ///
    /// Fails with a descriptive error string if the TOML is malformed.  Because the TOML is
    /// embedded at compile time, a parse failure at runtime indicates a build configuration
    /// problem rather than a missing file.
    pub fn load() -> Result<Self, String> {
        toml::from_str(CORPUS_TOML).map_err(|e| format!("corpus parse error: {e}"))
    }

    /// Validate the corpus and return summary statistics.  Fails on any integrity violation.
    ///
    /// # Checks performed (in order)
    /// 1. `detector_count` header == `detectors.len()`.
    /// 2. All `detector_id` strings are unique (collected into a `BTreeSet` for O(log n) lookup;
    ///    `BTreeSet` rather than `HashSet` for deterministic ordering in error messages).
    /// 3. No two entries share an identical canonical-definition fingerprint.
    ///    - First pass: fingerprint over `family|primitive_family|mathematical_form|
    ///      decision_functional|witness_role|fusion_axes` (the definition excluding name/id).
    ///    - If the first-pass hash collides, a second pass adds `source_basis|display_name`
    ///      to distinguish detectors that are genuinely distinct but share a primitive form.
    ///    - If both passes collide, the entry is a true duplicate and validation fails.
    ///
    /// The iteration order over `self.detectors` is the TOML parse order (top-to-bottom), which
    /// is deterministic for a fixed TOML file.
    pub fn validate(&self) -> Result<CorpusValidation, String> {
        if self.detector_count != self.detectors.len() {
            return Err(format!(
                "declared detector_count {} != entries {}",
                self.detector_count,
                self.detectors.len()
            ));
        }
        let mut ids = BTreeSet::new(); // accumulates detector_id strings; collision = duplicate
        let mut defs = BTreeSet::new(); // accumulates definition fingerprints; collision checked below
        let mut prims = BTreeSet::new(); // accumulates primitive_family values for family count
        let mut n_exec = 0;
        for d in &self.detectors {
            if !ids.insert(d.detector_id.clone()) {
                return Err(format!("duplicate detector_id: {}", d.detector_id));
            }
            // First-pass fingerprint: canonical definition excluding name and source_basis so
            // that genuinely identical algorithms (different names, same math) are flagged.
            // Canonical definition fingerprint (excludes id/name so genuine duplicates are caught).
            let def = format!(
                "{}|{}|{}|{}|{}|{}",
                d.family,
                d.primitive_family,
                d.mathematical_form,
                d.decision_functional,
                d.witness_role,
                d.fusion_axes.join(",")
            );
            if !defs.insert(sha256_hex(def.as_bytes())) {
                // First-pass collision: two entries share primitive form.
                // Distinct detectors may legitimately share a primitive form; only flag exact dupes
                // of the *full* definition tuple including source basis.
                let full = format!("{def}|{}|{}", d.source_basis, d.display_name);
                if !defs.insert(sha256_hex(full.as_bytes())) {
                    // Second-pass collision: full definition is truly identical — flag as duplicate.
                    return Err(format!(
                        "duplicate canonical definition near: {}",
                        d.detector_id
                    ));
                }
            }
            prims.insert(d.primitive_family.clone());
            if d.implementation_status == "Executed" {
                n_exec += 1;
            }
        }
        Ok(CorpusValidation {
            n_total: self.detectors.len(),
            n_executed: n_exec,
            n_catalogued: self.detectors.len() - n_exec,
            n_primitive_families: prims.len(),
            // SHA-256 of the raw TOML bytes; stable for any binary built from the same source.
            corpus_sha256: sha256_hex(CORPUS_TOML.as_bytes()),
        })
    }

    /// Iterator over the 18 executed detectors (those with `implementation_status == "Executed"`).
    ///
    /// Order follows the TOML parse order, which is the canonical `canonical_id` sequence.
    /// Used to cross-check that every executed detector ID has a corpus entry --- a *set-membership*
    /// check; the runtime `build_bank` order (detectors.rs) is independent of this sequence.
    pub fn executed(&self) -> impl Iterator<Item = &CorpusDetector> {
        self.detectors
            .iter()
            .filter(|d| d.implementation_status == "Executed")
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Smoke test: verifies the embedded corpus parses, passes all integrity checks, and matches
    /// the expected corpus counts (57 total, 18 executed, ≥ 10 primitive families).
    /// This test will fail at build time if `chemometric_atlas.toml` is corrupted or the counts
    /// drift from the declared values — acting as a compile-time corpus integrity gate.
    #[test]
    fn corpus_loads_and_validates() {
        let c = Corpus::load().expect("corpus loads");
        let v = c.validate().expect("corpus validates");
        assert_eq!(v.n_total, 57);
        assert_eq!(v.n_executed, 18); // Phase-C: mewma+dpca+mosum+mmd promoted Catalogued→Executed (14→18; total 57 unchanged)
        assert!(
            v.n_primitive_families >= 10,
            "expected a broad primitive-family spread"
        );
    }
}
