#!/usr/bin/env bash
# scripts/build_paper.sh — Compile paper/dsfb_oil_gas.tex to PDF.
#
# Usage: bash scripts/build_paper.sh [--clean]
#
# Environment (optional):
#   DSFB_OUTPUT   If set, compiles directly inside $DSFB_OUTPUT/paper/ so that
#                 ../figures/ resolves to the figures generated by build_figures.sh.
#                 If not set, compiles in-place from crates/dsfb-oil-gas/paper/.
#
# Requires: pdflatex and bibtex (TeX Live 2022+ recommended).

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC_PAPER_DIR="${REPO_ROOT}/paper"
TEX_FILE="dsfb_oil_gas.tex"
BIB_FILE="bibliography.bib"

# ── Compilation directory ────────────────────────────────────────────────────
# If DSFB_OUTPUT is set, compile in-place there so that ../figures/ resolves
# to $DSFB_OUTPUT/figures/ (where build_figures.sh deposited the PDFs).
# Otherwise compile directly from the crate's paper/ directory (standalone mode;
# requires figures to already exist at crates/dsfb-oil-gas/figures/).
if [[ -n "${DSFB_OUTPUT:-}" ]]; then
    PAPER_DIR="${DSFB_OUTPUT}/paper"
    mkdir -p "${PAPER_DIR}"
    cp "${SRC_PAPER_DIR}/${TEX_FILE}" "${PAPER_DIR}/${TEX_FILE}"
    [[ -f "${SRC_PAPER_DIR}/${BIB_FILE}" ]] && cp "${SRC_PAPER_DIR}/${BIB_FILE}" "${PAPER_DIR}/${BIB_FILE}" || true
else
    PAPER_DIR="${SRC_PAPER_DIR}"
fi

cd "${PAPER_DIR}"

echo "=== DSFB Paper Build ==="
echo "Working directory: ${PAPER_DIR}"
echo "Source: ${TEX_FILE}"

if [[ "${1:-}" == "--clean" ]]; then
    echo "--- Cleaning auxiliary files ---"
    rm -f *.aux *.log *.bbl *.blg *.out *.toc *.synctex.gz
    echo "Clean complete."
fi

# Check prerequisites
if ! command -v pdflatex &>/dev/null; then
    echo "ERROR: pdflatex not found. Install TeX Live: sudo apt install texlive-full"
    exit 1
fi
if ! command -v bibtex &>/dev/null; then
    echo "ERROR: bibtex not found. Install TeX Live: sudo apt install texlive-full"
    exit 1
fi

echo ""
echo "--- Pass 1: pdflatex (initial) ---"
pdflatex -interaction=nonstopmode -halt-on-error "${TEX_FILE}" \
    | grep -E "^!" || true

echo ""
echo "--- Pass 2: bibtex ---"
bibtex "${TEX_FILE%.tex}" 2>&1 | grep -v "^This is BibTeX" || true

echo ""
echo "--- Pass 3: pdflatex (resolve cross-references) ---"
pdflatex -interaction=nonstopmode -halt-on-error "${TEX_FILE}" \
    | grep -E "^!" || true

echo ""
echo "--- Pass 4: pdflatex (final) ---"
pdflatex -interaction=nonstopmode -halt-on-error "${TEX_FILE}" \
    | grep -E "(Warning|Error|Output written)" | tail -10 || true

PDF="${TEX_FILE%.tex}.pdf"
if [[ -f "${PDF}" ]]; then
    SIZE=$(du -sh "${PDF}" | cut -f1)
    PAGES=$(pdfinfo "${PDF}" 2>/dev/null | grep "^Pages:" | awk '{print $2}' || echo "unknown")
    echo ""
    echo "=== Build successful ==="
    echo "  File : ${PAPER_DIR}/${PDF}"
    echo "  Size : ${SIZE}"
    echo "  Pages: ${PAGES}"
else
    echo "ERROR: PDF not produced. Check ${TEX_FILE%.tex}.log for details."
    exit 1
fi
